#
# This makefile was expanded from makefile-1 by Telelogic.
# Expanded macros and dependencies may be found at the
# end of this file
#

#       Makefile Header:
#       Subsystem:
#       Description:
#       %created_by: guag %
#       %date_created: Fri Sep 30 10:04:34 2005 %


PREFIXBIN= ../../bin/

SHELLFILES= postproc.tix build_comp_win.tix leggif14varvalue.tcl umconv.tcl

IMGFILE=

ALLFILES =  $(SHELLFILES) $(IMGFILE)

ALLFILESBIN=$(PREFIXBIN)postproc.tix $(PREFIXBIN)build_comp_win.tix \
$(PREFIXBIN)leggif14varvalue.tcl $(PREFIXBIN)umconv.tcl

all: $(ALLFILESBIN) makefile

debug:
	echo $(ALLFILES)
	echo $(ALLFILESBIN)


$(PREFIXBIN)postproc.tix         : postproc.tix
	cp $? $(PREFIXBIN)
$(PREFIXBIN)build_comp_win.tix   : build_comp_win.tix
	cp $? $(PREFIXBIN)
$(PREFIXBIN)edit_tasks_v3.tix    : edit_tasks_v3.tix
	cp $? $(PREFIXBIN)
$(PREFIXBIN)leggif14varvalue.tcl : leggif14varvalue.tcl
	cp $? $(PREFIXBIN)
$(PREFIXBIN)umconv.tcl           : umconv.tcl
	cp $? $(PREFIXBIN)






# ******* Telelogic expanded section *******

# make_macros from project "Alg_legopc-2007A1_RHE4_lomgr
#CFLAGS = -g -Wall
F_FLAGS=-fno-second-underscore -g -fno-automatic -finit-local-zero
CFLAGS = -Wall -DLinux
CC = gcc
