/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/*
        deflag.inc definizione flag
*/
extern char *sigfan[];
extern char *sigfaa[];
extern char *sigfdi[];
extern char *sigftr[];
extern char *sigfor[];
extern char *sigfat[];


