/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/*
        intestdi.inc
        contiene tutte le scritte della function intestdi

	17 Gennaio 1994 modifiche per gestione scritte a
			piu' lingue
*/

	extern char *stato_0;
        extern char *stato_1;
	extern char ** tipodi;


