/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/

/* ->INTESTAN.INC
        intestan.inc
        contiene tutte le scritte della function intestaa

	17 Gennaio 1994		Modifiche per gestione 
				stringhe con lingue diverse
*/

extern char *sa_s;
extern char *sb_s;
extern char *ca_s;
extern char *cb_s;

extern char **tipoan;


