/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/*
        definizione delle scritte utilizzate dalla
        function mandb

        17 Gennaio 1994  modifiche per scritte a piu' lingue
*/
        extern char *istruzione;
        extern char *nome_punto;
        extern char *non_accetto;
        extern char *operazioni;
        extern char *quale_misura;

