/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/*
        modfan.inc
        definizione delle stringhe delle functions modf-- 

        17 Gennaio 1944  modifiche per scritte a piu' lingue
*/
        extern char *valori_flag;
        extern char *nuovo_valore;


