/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/*
        modfdi.inc
        definizione delle stringhe delle functions modf-- 

        17 Gennaio 1994  modifiche per scritte a piu' lingue
*/
        extern char *status_flag;
        extern char *nuovo_valore;
        extern char *st0s; 
        extern char *st1s; 
        extern char *inv_com;
