/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/*
        modfor.inc
        definizione delle stringhe della function modfor

        17 Gennaio 1994  modifiche per scritte a piu' lingue
*/
        extern char *status_flag;
        extern char *nuovo_stato;


