/**********************************************************************
*
*       C Header:               editdd.h
*       Subsystem:              1
*       Description:
*       %created_by:    lomgr %
*       %date_created:  Thu Jul 31 17:10:52 2003 %
*
**********************************************************************/

#ifndef h_editdd_h
#define h_editdd_h

STRUCT_TABLE editddnocab[]={
        {"Sigla",          TIPO_CHAR,0,     "" },
        {"Descrizione",    TIPO_CHAR,0,     ""},
        {"IndDB",   TIPO_INT,      0  ,""},
        {"Stato0",    TIPO_CHAR,0,     "" },
        {"Stato1",    TIPO_CHAR,0,     "" },
        {"TagPP1",    TIPO_CHAR,0,     "" },
        {"TagPP2",    TIPO_CHAR,0,     "" },
        {"TInib",    TIPO_CHAR,0,     "" },
        {"Zonaimpianto",   TIPO_INT,      0  ,""},
        {"Trattamento",    TIPO_INT,      0 ,""},
        {"Severita",       TIPO_INT,      0   ,""},
        {"Note",           TIPO_CHAR,0,     "" },
        {"Dainstallare", TIPO_BOOLEAN,0,"No"},
        {"Gerarchia",      TIPO_CHAR,0,     ""  }
        };

#define NUM_CAMPI_EDITDD_NOCAB sizeof(editddnocab)/sizeof(STRUCT_TABLE)

struct struct_table_cab_st
        {
        char riga[500];
        };

typedef struct struct_table_cab_st STRUCT_TABLE_CAB;

STRUCT_TABLE_CAB editdd[]={
{"\"Sigla\";\"Descrizione\";\"IndDB\";\"Stato0\";\"Stato1\";\"TagPP1\";\"TagPP2\";\"TInib\";\"Zonaimpianto\";\"Trattamento\";\"Severita\";\"Note\";\"Dainstallare\";\"Gerarchia\""},
{"\"STVIDEO1\";\"VIDEO OPERATORE 1\";0;\"NORMALE\";\"GUASTO\";;;1;0;2;1;;0;"},
{"\"STVIDEO2\";\"VIDEO OPERATORE 2\";1;\"NORMALE\";\"GUASTO\";;;1;0;2;1;;0;"},
{"\"STVIDEO3\";\"VIDEO OPERATORE 3\";2;\"NORMALE\";\"GUASTO\";;;1;0;2;1;;0;"},
{"\"STVIDEO4\";\"VIDEO OPERATORE 4\";3;\"NORMALE\";\"GUASTO\";;;1;0;2;1;;0;"},
{"\"STVIDEO5\";\"VIDEO OPERATORE 5\";4;\"NORMALE\";\"GUASTO\";;;1;0;2;1;;0;"},
{"\"STVIDEO6\";\"VIDEO OPERATORE 6\";5;\"NORMALE\";\"GUASTO\";;;1;0;2;1;;0;"},
{"\"STVIDEO7\";\"VIDEO OPERATORE 7\";6;\"NORMALE\";\"GUASTO\";;;1;0;2;1;;0;"},
{"\"STVIDEO8\";\"VIDEO OPERATORE 8\";7;\"NORMALE\";\"GUASTO\";;;1;0;2;1;;0;"},
{"\"STVIDEO9\";\"VIDEO OPERATORE 9\";8;\"NORMALE\";\"GUASTO\";;;1;0;2;1;;0;"},
{"\"STPRN5\";\"STAMPANTE 5\";9;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STPRN6\";\"STAMPANTE 6\";10;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STPRN4\";\"STAMPANTE 4\";11;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STPRN3\";\"STAMPANTE 3\";12;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STPRN1\";\"STAMPANTE 1\";13;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STPRN2\";\"STAMPANTE 2\";14;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STPRN7\";\"STAMPANTE 7\";94;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STPRN8\";\"STAMPANTE 8\";95;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STHARDCOPY\";\"STAMPANTE HARD COPY\";15;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STCONFIG\";\"STATO CONFIG\";16;\"IN LINEA\";\"F. LINEA\";;;1;0;2;1;;0;"},
{"\"DISKERR\";\"ERRORE FLOPPY\";17;\"NORMALE\";\"ERRORE\";;;1;0;2;1;;0;"},
{"\"STDISK\";\"STATO DISCO\";18;;\"PIENO\";;;1;0;2;1;;0;"},
{"\"LBGFULL\";\"FILE REG. LIBRO GIORN.\";19;\"DISPONIB\";\"ESAURITI\";;;1;0;2;1;;0;"},
{"\"LOCKARC\";\"STATO RISORSA ARCHIVI\";20;\"LIBERA\";\"IN USO\";;;1;0;2;1;;0;"},
{"\"STINT\";\"SCHEDA INT\";64;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STDOU\";\"SCHEDA DOU\";65;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STCOM1\";\"SCHEDA COMMUTAZIONE COM1\";56;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STCOM2\";\"SCHEDA COMMUTAZIONE COM2\";57;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STCOM3\";\"SCHEDA COMMUTAZIONE COM3\";58;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STCOM4\";\"SCHEDA COMMUTAZIONE COM4\";59;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STCOM5\";\"SCHEDA COMMUTAZIONE COM5\";60;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STCOM6\";\"SCHEDA COMMUTAZIONE COM6\";61;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STCOM7\";\"SCHEDA COMMUTAZIONE CMT\";62;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"STCOM8\";\"SCHEDA COMMUTAZIONE COM8\";63;\"NORMALE\";\"GUASTA\";;;1;0;2;1;;0;"},
{"\"ABCOM1\";\"SCHEDA COM1 COMMUTATA SU\";70;\"MICRO A\";\"MICRO B\";;;1;0;2;1;;0;"},
{"\"ABCOM2\";\"SCHEDA COM2 COMMUTATA SU\";71;\"MICRO A\";\"MICRO B\";;;1;0;2;1;;0;"},
{"\"ABCOM3\";\"SCHEDA COM3 COMMUTATA SU\";72;\"MICRO A\";\"MICRO B\";;;1;0;2;1;;0;"},
{"\"ABCOM4\";\"SCHEDA COM4 COMMUTATA SU\";73;\"MICRO A\";\"MICRO B\";;;1;0;2;1;;0;"},
{"\"ABCOM5\";\"SCHEDA COM5 COMMUTATA SU\";74;\"MICRO A\";\"MICRO B\";;;1;0;2;1;;0;"},
{"\"ABCOM6\";\"SCHEDA COM6 COMMUTATA SU\";75;\"MICRO A\";\"MICRO B\";;;1;0;2;1;;0;"},
{"\"ABCOM7\";\"SCHEDA CMT  COMMUTATA SU\";76;\"MICRO A\";\"MICRO B\";;;1;0;2;1;;0;"},
{"\"ABCOM8\";\"SCHEDA COM8 COMMUTATA SU\";77;\"MICRO A\";\"MICRO B\";;;1;0;2;1;;0;"},
{"\"MACOM1\";\"SCHEDA COM1 COMMUTATA IN\";78;\"MANUALE\";\"AUTOMAT.\";;;1;0;2;1;;0;"},
{"\"MACOM2\";\"SCHEDA COM2 COMMUTATA IN\";79;\"MANUALE\";\"AUTOMAT.\";;;1;0;2;1;;0;"},
{"\"MACOM3\";\"SCHEDA COM3 COMMUTATA IN\";80;\"MANUALE\";\"AUTOMAT.\";;;1;0;2;1;;0;"},
{"\"MACOM4\";\"SCHEDA COM4 COMMUTATA IN\";81;\"MANUALE\";\"AUTOMAT.\";;;1;0;2;1;;0;"},
{"\"MACOM5\";\"SCHEDA COM5 COMMUTATA IN\";82;\"MANUALE\";\"AUTOMAT.\";;;1;0;2;1;;0;"},
{"\"MACOM6\";\"SCHEDA COM6 COMMUTATA IN\";83;\"MANUALE\";\"AUTOMAT.\";;;1;0;2;1;;0;"},
{"\"MACOM7\";\"SCHEDA CMT  COMMUTATA IN\";84;\"MANUALE\";\"AUTOMAT.\";;;1;0;2;1;;0;"},
{"\"MACOM8\";\"SCHEDA COM8 COMMUTATA IN\";85;\"MANUALE\";\"AUTOMAT.\";;;1;0;2;1;;0;"},
{"\"RICALL01\";\"RICONOSCIUTI ALLARMI DB1\";42;;;;;1;0;1;1;;0;"},
{"\"RICALL02\";\"RICONOSCIUTI ALLARMI DB2\";43;;;;;1;0;1;1;;0;"},
{"\"RICALL03\";\"RICONOSCIUTI ALLARMI DB3\";44;;;;;1;0;1;1;;0;"},
{"\"RICALL04\";\"RICONOSCIUTI ALLARMI DB4\";45;;;;;1;0;1;1;;0;"},
{"\"RICALL05\";\"RICONOSCIUTI ALLARMI DB5\";46;;;;;1;0;1;1;;0;"},
{"\"RICALL06\";\"RICONOSCIUTI ALLARMI DB6\";47;;;;;1;0;1;1;;0;"},
{"\"NOALL01\";\"NESSUN ALLARME IN DB1\";48;;;;;1;0;1;1;;0;"},
{"\"NOALL02\";\"NESSUN ALLARME IN DB2\";49;;;;;1;0;1;1;;0;"},
{"\"NOALL03\";\"NESSUN ALLARME IN DB3\";50;;;;;1;0;1;1;;0;"},
{"\"NOALL04\";\"NESSUN ALLARME IN DB4\";51;;;;;1;0;1;1;;0;"},
{"\"NOALL05\";\"NESSUN ALLARME IN DB5\";52;;;;;1;0;1;1;;0;"},
{"\"NOALL06\";\"NESSUN ALLARME IN DB6\";53;;;;;1;0;1;1;;0;"},
{"\"OLDSYSDATE\";\"CAMBIO DATA/ORA SISTEMA\";54;;;;;1;0;1;1;;0;"},
{"\"NEWSYSDATE\";\"NUOVA DATA/ORA\";55;;;;;1;0;1;1;;0;"},
{"\"STDINT1\";\"STATO DIGITALE 1 INT\";86;;;;;1;0;1;1;;0;"},
{"\"STDINT2\";\"STATO DIGITALE 2 INT\";87;;;;;1;0;1;1;;0;"},
{"\"STDINT3\";\"STATO DIGITALE 3 INT\";88;;;;;1;0;1;1;;0;"},
{"\"STDINT4\";\"STATO DIGITALE 4 INT\";89;;;;;1;0;1;1;;0;"},
{"\"STDINT5\";\"STATO DIGITALE 5 INT\";90;;;;;1;0;1;1;;0;"},
{"\"STDINT6\";\"TACITAZIONE CICALINO\";91;\"OFF LINE\";\"ON LINE\";;;1;0;1;1;;0;"},
{"\"RCESTAMPA\";\"ABILITAZIONE STAMPA RCE\";104;\"ABIL.\";\"DISABIL.\";;;1;0;2;1;;0;"},
{"\"STSCC\";\"COLLEGAMENTO SCC/SDS\";105;\"PRESENTE\";\"ASSENTE\";;;1;0;2;1;;0;"},
{"\"STISA01\";\"STATO COMUN. NODO ISA 01\";36;\"ON LINE\";\"OFF LINE\";;;1;0;2;1;;0;"},
{"\"STISA02\";\"STATO COMUN. NODO ISA 02\";37;\"ON LINE\";\"OFF LINE\";;;1;0;2;1;;0;"},
{"\"STISA03\";\"STATO COMUN. NODO ISA 03\";38;\"ON LINE\";\"OFF LINE\";;;1;0;2;1;;0;"},
{"\"STISA04\";\"STATO COMUN. NODO ISA 04\";39;\"ON LINE\";\"OFF LINE\";;;1;0;2;1;;0;"},
{"\"STWDA\";\"STATO WATCH DOG A\";68;\"ASSENTE\";\"PRESENTE\";;;1;0;2;1;;0;"},
{"\"STWDB\";\"STATO WATCH DOG B\";67;\"ASSENTE\";\"PRESENTE\";;;1;0;2;1;;0;"},
{"\"SYSAB\";\"SISTEMA A O B\";69;\"A\";\"B\";;;1;0;0;1;;0;"},
{"\"MASTER\";\"SISTEMA MASTER O SLAVE\";66;\"SLAVE\";\"MASTER\";;;1;0;0;1;;0;"},
{"\"SLAVEINIZ\";\"SLAVE IN INIZIALIZZ.\";100;\"CONCLUSA\";\"IN CORSO\";;;1;0;4;1;;0;"},
{"\"SLAVEAGG\";\"SLAVE AGGIORNATO\";101;\"NON AGG.\";\"AGGIORN.\";;;1;0;2;1;;0;"},
{"\"SLAVEON\";\"SLAVE IN LINEA\";102;\"NON CONN\";\"CONNESSO\";;;1;0;2;1;;0;"},
{"\"STLINK\";\"COMUNICAZ. MASTER SLAVE\";103;\"ON LINE\";\"OFF LINE\";;;1;0;2;1;;0;"},
{"\"STALIMA\";\"STATO ALIMENTATORE A\";93;\"OFF LINE\";\"ON LINE\";;;1;0;2;1;;0;"},
{"\"STALIMB\";\"STATO ALIMENTATORE B\";92;\"OFF LINE\";\"ON LINE\";;;1;0;2;1;;0;"},
{"\"LOCKFLOPPY\";\"STATO DEL FLOPPY\";108;\"LIBERO\";\"OCCUPATO\";;;1;0;0;1;;0;"},
{"\"LBGFULL1\";\"FILE REG. LIBRO GIORN. 1\";180;\"DISPON.\";\"ESAURITI\";;;1;0;2;1;;0;"},
{"\"LBGFULL2\";\"FILE REG. LIBRO GIORN. 2\";181;\"DISPON.\";\"ESAURITI\";;;1;0;2;1;;0;"},
{"\"LBGFULL3\";\"FILE REG. LIBRO GIORN. 3\";182;\"DISPON.\";\"ESAURITI\";;;1;0;2;1;;0;"},
{"\"LBGFULL4\";\"FILE REG. LIBRO GIORN. 4\";183;\"DISPON.\";\"ESAURITI\";;;1;0;2;1;;0;"},
{"\"LBGFULL5\";\"FILE REG. LIBRO GIORN. 5\";184;\"DISPON.\";\"ESAURITI\";;;1;0;2;1;;0;"},
{"\"LBGFULL6\";\"FILE REG. LIBRO GIORN. 6\";185;\"DISPON.\";\"ESAURITI\";;;1;0;2;1;;0;"},
{"\"LBGFULL7\";\"FILE REG. LIBRO GIORN. 7\";186;\"DISPON.\";\"ESAURITI\";;;1;0;2;1;;0;"},
{"\"LBGFULL8\";\"FILE REG. LIBRO GIORN. 8\";187;\"DISPON.\";\"ESAURITI\";;;1;0;2;1;;0;"},
{"\"STO-STA1\";\"PAS 1 SU STOP STOPIDR\";32;\"FERMO\";\"ATTIVO\";;;1;0;2;1;;0;"},
{"\"RUN-FRE1\";\"PAS 1 SU STOP STOPIDR\";33;\"RUN\";\"FREEZE\";;;1;0;2;1;;0;"},
{"\"STO-STA2\";\"PAS 2 SU STOP PASDISP\";34;\"FERMO\";\"ATTIVO\";;;1;0;2;1;;0;"},
{"\"RUN-FRE2\";\"PAS 2 SU STOP PASDISP\";35;\"RUN\";\"FREEZE\";;;1;0;2;1;;0;"},
{"\"0ARC-ST01\";\"STATO ARCHIVIO  1\";21;;\"IN USO\";;;1;0;2;1;;0;"},
{"\"0ARC-ST02\";\"STATO ARCHIVIO  2\";22;;\"IN USO\";;;1;0;2;1;;0;"},
{"\"0ARC-ST03\";\"STATO ARCHIVIO  3\";23;;\"IN USO\";;;1;0;2;1;;0;"},
{"\"0ARC-ST04\";\"STATO ARCHIVIO  4\";24;;\"IN USO\";;;1;0;2;1;;0;"},
{"\"0ARC-ST05\";\"STATO ARCHIVIO  5\";25;;\"IN USO\";;;1;0;2;1;;0;"},
{"\"0ARC-ST06\";\"STATO ARCHIVIO  6\";26;;\"IN USO\";;;1;0;2;1;;0;"},
{"\"0ARC-ST07\";\"STATO ARCHIVIO  7\";27;;\"IN USO\";;;1;0;2;1;;0;"},
{"\"0ARC-ST08\";\"STATO ARCHIVIO  8\";28;;\"IN USO\";;;1;0;2;1;;0;"},
{"\"SSCSTOP\";\"SUPERVISORE IN STOP\";139;\"ON\";\"OFF\";;;1;0;0;;;0;"},
{"\"SSCWAIT\";\"SUPERVISORE IN WAIT\";140;\"ON\";\"OFF\";;;1;0;0;;;0;"},
{"\"SSCREADY\";\"SUPERVISORE IN READY\";141;\"ON\";\"OFF\";;;1;0;0;;;0;"},
{"\"SSCRUN\";\"STATO SUPERVISORE\";142;\"RUN\";\"FREEZE\";;;1;0;2;;;0;"},
{"\"SSCFREEZE\";\"SUPERVISORE IN FREEZE\";143;\"ON\";\"OFF\";;;1;0;0;;;0;"},
{"\"SSCSIMON\";\"SIMULATORE\";146;\"CONNESSO\";\"NON CONN\";;;1;0;2;;;0;"},
{"\"SSCBKTK\";\"SUPERVISORE IN BACKTRACK\";144;\"ON\";\"OFF\";;;1;0;0;;;0;"},
{"\"SSCREPLAY\";\"SUPERVISORE IN REPLAY\";145;\"ON\";\"OFF\";;;1;0;0;;;0;"},
{"\"SSCNOCOM\";\"COMANDO VERSO SIMULATORE\";147;\"RICEVUTO\";\"FALLITO\";;;1;0;2;;;0;"},
{"\"STCICALINO\";\"STATO DEL CICALINO\";150;\"OFF\";\"ON\";;;1;0;0;;;0;"},
	};

#define NUM_RECORD_EDITDD sizeof(editdd)/sizeof(STRUCT_TABLE_CAB)
#endif
