#FROM python:3.9.1
# FROM fedora:41

# RUN dnf update -y
# RUN dnf install -y git && dnf install -y f77 && dnf install -y gcc && dnf install -y gfortran
# RUN dnf install -y fastfetch && dnf install -y xclock && dnf install -y xhost
# RUN dnf install -y libX11-devel && dnf install -y motif-devel && dnf install -y sqlite-devel && dnf install -y libbsd-devel
# RUN dnf install -y tcl tk tix &&  dnf install -y ncurses-devel &&  dnf install -y gdbm-devel
# RUN dnf install -y hostname && dnf install -y glibc-langpack-en
# RUN dnf install -y which

# RUN dnf clean all

# RUN mkdir /home/legoroot_fedora41
# COPY /LegoPST2010A_WSL_DARHE6_64 /home/legoroot_fedora41 


# # Imposta le localizzazioni di base
# ENV LANG=en_US.UTF-8 \
#     LC_ALL=en_US.UTF-8 \
#     LANGUAGE=en_US:en

# RUN mkdir /home/app
# WORKDIR /home/app
# #ENTRYPOINT ["source /home/legoroot_fedora41/.profile_legoroot"]
# #CMD ["source /home/legoroot_fedora41/.profile_legoroot"]
# #CMD ["/bin/bash", "-c", "source /home/legoroot_fedora41/.profile_legoroot && exec /bin/bash -l"]
# #CMD bash -c "source /home/legoroot_fedora41/.profile_legoroot"
# CMD tail -f /dev/null
# #CMD ["python", "app/DT_main.py"]


#FROM python:3.9.1
FROM fedora:41

# Raggruppa le installazioni e aggiungi i pacchetti mancanti
RUN dnf update -y && \
    dnf install -y \
        git \
        # f77 è obsoleto, gfortran dovrebbe essere sufficiente per il codice Fortran 77
        # Altrimenti, gfortran è il compilatore Fortran moderno.
        gcc \
        gfortran \
        fastfetch \
        xterm \
        xclock \
        xhost \
        hostname \
        glibc-langpack-en \
        libX11-devel \
        motif-devel \
        sqlite-devel \
        libbsd-devel \
        tcl tk tix \
        ncurses-devel \
        leafpad \
        gdbm-devel \
        ksh \
        which && \
    dnf clean all # Pulisci la cache di dnf per ridurre la dimensione dell immagine

# Imposta le localizzazioni di base
ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    LANGUAGE=en_US:en

RUN mkdir /home/legoroot_fedora41
COPY /LegoPST2010A_WSL_DARHE6_64 /home/legoroot_fedora41

RUN mkdir /home/app
WORKDIR /home/app

# Opzione A: Esegui lo script ma assicurati che gestisca l'assenza di display
# Modifica .profile_legoroot come suggerito sopra per saltare xhost se DISPLAY non è valido
##RUN bash -c "source /home/legoroot_fedora41/.profile_legoroot"
#ENTRYPOINT bash -c "source /home/legoroot_fedora41/.profile_legoroot"
#####ENTRYPOINT ["bash", "-c", "source /home/legoroot_fedora41/.profile_legoroot /home/legoroot_fedora41"]

# Opzione B: Se .profile_legoroot è solo per sessioni interattive,
# considera di non sorgerlo qui e di farlo fare da .bashrc.
# In tal caso, le variabili d'ambiente necessarie per l'applicazione
# devono essere impostate con ENV.
# Esempio:
# RUN echo "source /home/legoroot_fedora41/.profile_legoroot" >> /root/.bashrc

CMD ["tail","-f","/dev/null"]
#CMD ["python", "app/DT_main.py"]
