#! /bin/bash
#
# Lancia il container LegoPST ed apre un terminale bash
#

docker run --rm -it  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/antonio:/root aguagliardi/legopst:latest bash -c "cd /root && source /home/legoroot_fedora41/.profile_legoroot && exec bash -l"

###docker run --rm -it  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/antonio:/root aguagliardi/legopst:latest bash; bash -c golgDock

##docker run --rm -it  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/antonio:/root aguagliardi/legopst:1.0 bash -c "source /home/legoroot_fedora41/.profile_legoroot && cd /root && exec /bin/bash -l"


# docker run --rm -it  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/antonio:/root aguagliardi/legopst:1.0 bash -c "source /home/legoroot_fedora41/.profile_legoroot && exec /bin/bash -l && cd /root"
#docker run --rm -it  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix aguagliardi/legopst:1.0 bash -c "source /home/legoroot_fedora41/.profile_legoroot && exec /bin/bash -l"
### docker run --rm -it  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix aguagliardi/legopst:1.0 /bin/bash
# docker compose run --rm LegoPSTServ /bin/bash
