/* Generated by IDL compiler version OSF DCE T1.1.0-03 with GNU Flex/Bison */
#ifndef conv_v3_0_included
#define conv_v3_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
extern void conv_who_are_you(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ uuid_t *actuid,
    /* [in] */ unsigned32 boot_time,
    /* [out] */ unsigned32 *seq,
    /* [out] */ unsigned32 *st
#endif
);
extern void conv_who_are_you2(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ uuid_t *actuid,
    /* [in] */ unsigned32 boot_time,
    /* [out] */ unsigned32 *seq,
    /* [out] */ uuid_t *cas_uuid,
    /* [out] */ unsigned32 *st
#endif
);
extern void conv_are_you_there(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ uuid_t *actuid,
    /* [in] */ unsigned32 boot_time,
    /* [out] */ unsigned32 *st
#endif
);
extern void conv_who_are_you_auth(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ uuid_t *actuid,
    /* [in] */ unsigned32 boot_time,
    /* [in] */ idl_byte in_data[],
    /* [in] */ signed32 in_len,
    /* [in] */ signed32 out_max_len,
    /* [out] */ unsigned32 *seq,
    /* [out] */ uuid_t *cas_uuid,
    /* [out] */ idl_byte out_data[],
    /* [out] */ signed32 *out_len,
    /* [out] */ unsigned32 *st
#endif
);
extern void conv_who_are_you_auth_more(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ uuid_t *actuid,
    /* [in] */ unsigned32 boot_time,
    /* [in] */ signed32 index,
    /* [in] */ signed32 out_max_len,
    /* [out] */ idl_byte out_data[],
    /* [out] */ signed32 *out_len,
    /* [out] */ unsigned32 *st
#endif
);
typedef struct conv_v3_0_epv_t {
void (*conv_who_are_you)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ uuid_t *actuid,
    /* [in] */ unsigned32 boot_time,
    /* [out] */ unsigned32 *seq,
    /* [out] */ unsigned32 *st
#endif
);
void (*conv_who_are_you2)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ uuid_t *actuid,
    /* [in] */ unsigned32 boot_time,
    /* [out] */ unsigned32 *seq,
    /* [out] */ uuid_t *cas_uuid,
    /* [out] */ unsigned32 *st
#endif
);
void (*conv_are_you_there)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ uuid_t *actuid,
    /* [in] */ unsigned32 boot_time,
    /* [out] */ unsigned32 *st
#endif
);
void (*conv_who_are_you_auth)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ uuid_t *actuid,
    /* [in] */ unsigned32 boot_time,
    /* [in] */ idl_byte in_data[],
    /* [in] */ signed32 in_len,
    /* [in] */ signed32 out_max_len,
    /* [out] */ unsigned32 *seq,
    /* [out] */ uuid_t *cas_uuid,
    /* [out] */ idl_byte out_data[],
    /* [out] */ signed32 *out_len,
    /* [out] */ unsigned32 *st
#endif
);
void (*conv_who_are_you_auth_more)(
#ifdef IDL_PROTOTYPES
    /* [in] */ handle_t h,
    /* [in] */ uuid_t *actuid,
    /* [in] */ unsigned32 boot_time,
    /* [in] */ signed32 index,
    /* [in] */ signed32 out_max_len,
    /* [out] */ idl_byte out_data[],
    /* [out] */ signed32 *out_len,
    /* [out] */ unsigned32 *st
#endif
);
} conv_v3_0_epv_t;
extern conv_v3_0_epv_t conv_v3_0_c_epv;
extern rpc_if_handle_t conv_v3_0_c_ifspec;
extern rpc_if_handle_t conv_v3_0_s_ifspec;

#ifdef __cplusplus
    }
#endif

#endif
