/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
#define PAGEUP		73	/* window up one page		*/
#define TRUE -1
#define PAGEDOWN	81	/* window down one page		*/
#define LEFT		75	/* cursor left one column	*/
#define RIGHT		77	/* cursor right one column	*/
#define UPARROW		72	/* cursor up one row		*/
#define DOWNARROW	80	/* cursor down one row		*/
#define HOME		71	/* cursor to home		*/
#define END		79	/* cursor to end of screen	*/
#define INS		82
#define RIT		8	/* ritorno indietro con cancellazione */	
#define DEL		83

#define KF1		59      /* tasto F1 usato per EDIT      */
#define KF2		60      /* tasto F2 usato per T_DATI    */
#define KF3		61      /* tasto F3 usato per PAGE_UP   */
#define KF4		62      /* tasto F4 usato per PAGE_DOWN */
#define KF5		63      /* tasto F5 usato per HELP      */
#define KF6		64      /* tasto F6 usato per CANCELL   */
#define KF7		65      /* tasto F7 usato per PRTCOLL   */
#define KF8		66      /* tasto F8 usato per USCITA    */
#define KF9		67      /*                              */
#define KF10   		68      /*                              */

#define AKF1	       104      /* tasto F1 con ALT             */
#define AKF2	       105      /* tasto F2 con ALT		*/
#define AKF3	       106      /* tasto F3 con ALT		*/
#define AKF4	       107      /* tasto F4 con ALT		*/
#define AKF5	       108      /* tasto F5 con ALT		*/
#define AKF6	       109      /* tasto F6 con ALT		*/
#define AKF7	       110      /* tasto F7 con ALT		*/
#define AKF8	       111      /* tasto F8 con ALT		*/
#define AKF9	       112      /*                              */
#define AKF10          113      /*                              */

#define KSF1 84
#define KSF2 85
#define KSF3 86
#define KSF4 87
#define KSF5 88
#define KSF6 89
#define KSF7 90
#define KSF8 91
#define KSF9 92
#define KSF0 93

#define KCF1 94
#define KCF2 95
#define KCF3 96
#define KCF4 97
#define KCF5 98
#define KCF6 99
#define KCF7 100
#define KCF8 101
#define KCF9 102
#define KCF0 103 


#define TAB              9
#define BACK             8

#define	CR		13
#define ESC		27
