/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/

#define max_zone        32              // n. massimo zone di impianto
#define max_dbsall       6              // n. massimo dbs allarmi
#define num_pall         1              // per compatibilita' con vecchi allarmi
                                        // utilizzato da init.c
#define nall_vi         16              // n. allarmi visualizzati alla volta

