/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/*
	il file di include svindia.inc contiene i define relativi
	agli offset nella tabella svi_dia del task scgev.c per la
	gestione della diagnostica del sistema
*/
/*
	diagnostica rete Com rete 
*/
#define	all_nodo_config		72
#define all_nodo_stop_1		77
#define all_nodo_stop_2		80
#define all_nodo_armadi		83
#define last_all_nodo_armadi    124
/*
	diagnostica files libro giornale in esaurimento
*/
#define all_lbgfull	       169	
