/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/* ->TABULATI.INC
 *	E'condiviso dalle funzioni tabper() e tabul() e contiene la copia
 *	del file dizionario dei tabulati.
 */
#include "defpub.h"

pub S_DIZTAB  diztab[n_tabu];	  
extern short mbox_tabul;		/* mail box tabulati	*/
#define l_mstab sizeof(S_STAB)

