/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/*   TXETH.INC

        definizione variabili globali per trasmissione rete ethernet
                        
        20 Ottobre 1992   Rel. 0.0   R.Lassini
*/
#include "defpub.h"

pub short nd;          // descrittore nodo rete
pub short num_mes;     // contatore del numero di messaggi trasmessi a scada
//short ritardo;     // ritardo per trasmissione      
