#
# This makefile was expanded from makefile-1 by Telelogic.
# Expanded macros and dependencies may be found at the
# end of this file
#

TARGETBIN = ../../bin
LIBS =  -lm
INCLUDES =
SRCS = inhoud.c

all: ${TARGETBIN}/inhoud

# The variable $@ has the value of the target.
${TARGETBIN}/inhoud: inhoud.c
	${CC} ${CFLAGS} ${INCLUDES} -g -o $@ $? ${LIBS}


clean:
	rm *.o core *~

# ******* Telelogic expanded section *******

# make_macros from project "Alg_legopc-2007A1_RHE4_lomgr
#CFLAGS = -g -Wall
F_FLAGS=-fno-second-underscore -g -fno-automatic -finit-local-zero
CFLAGS = -Wall -DLinux
CC = gcc
