/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/* File di include contenente la definizione dei path completi che */
/* individuano i file di include privati del compilatore           */

#define define   "\comppol\define.inc"

#define chascii  "\comppol\chascii.inc"

#define tipi     "\comppol\tipi.h"
