C*************************************************************************
C
C      PROGRAMMA PER CALCOLARE IL REGIME STAZIONARIO DI UNO SCHEMA DI 
C      REGOLAZIONE .
C      versione per UNIX	
C	
C*************************************************************************
      CHARACTER*4 SCHEMA,LG,SCHLOW
      CHARACTER*10 SYMB_VAR,VALUE
      CHARACTER*80 NOME_FILE14, NOME_FILE04
      CHARACTER*80 DESCR
      CHARACTER*132 LINE
      PARAMETER (N000=5000)
      DIMENSION VAR(N000,2),XYU(N000),DATI(N000)
      DIMENSION CNXYU(1),TOL(1),AJAC(1,1),RNI(1)
      COMMON/REGIME/KREGIM
      COMMON/PARPAR/NUL(7),ITERT
      LOGICAL KREGIM
      CHARACTER*100  LISTA(N000)
C
      MX1=N000
      MX5=1
C
C_____ APERTURA DELLE TAVOLE
C
      CALL INITSM
C
C____ APERTURA DEL FILE 14 PRODOTTO DA LEGOGRAF
C      
      OPEN(UNIT=14,FILE='f14.dat',STATUS='OLD')
C
C____ LETTURA DEI DATI SU FILE 14
C
      DO I=1,4 
      READ(14,'(A)')
      ENDDO
C
      I=0
C
C____ LETTURA DEI SIMBOLI E DEI VALORI DELLE USCITE
   1  READ(14,1000)LG,SYMB_VAR,VALUE,DESCR
 1000 FORMAT(A,A,A,A)
      IF(LG.NE.'*LG*') THEN
       I=I+1
       READ(SYMB_VAR,'(2A4)')VAR(I,1),VAR(I,2)
       READ(VALUE,'(F10.0)')XYU(I)
       LISTA(I) = SYMB_VAR(1:8)//' --UA-- '//DESCR(22:)
       GO TO 1
      ELSE
       NU=I
      ENDIF
C
C____ LETTURA DEI SIMBOLI E DEI VALORI DEGLI INGRESSI
   2  READ(14,1000)LG,SYMB_VAR,VALUE,DESCR
      IF(LG.NE.'*LG*') THEN
       I=I+1
       READ(SYMB_VAR,'(2A4)')VAR(I,1),VAR(I,2)
       READ(VALUE,'(F10.0)')XYU(I)
       LISTA(I) = SYMB_VAR(1:8)//' --IN-- '//DESCR(22:)
       GO TO 2
      ELSE
       NI=I-NU
      ENDIF
C
C_____ CHIAMATA ALLA SUBROUTINE "I2" DELLO SCHEMA DI REGOLAZIONE PER 
C      LA LETTURA DEI DATI DA FILE 14
C
      IFUN=2
      IV1=1
      IV2=NU+NI
      ID1=1
      ID2=1
      IER=0
C$C      
      CALL ####I2(IFUN,VAR,MX1,IV1,IV2,XYU,DATI,ID1,ID2,
     $            IBL1,IBL2,IER,CNXYU,TOL)
C$C
C
C_____ CHIAMATA ALLA SUBROUTINE "C1" DELLO SCHEMA DI REGOLAZIONE PER 
C      IL CALCOLO DELLO STAZIONARIO
C
      ITERT=-1
      KREGIM=.TRUE.
      NDATI = ID2-1
      IFUN=2
C$C      
      CALL ####C1(IFUN,AJAC,MX5,IV1,XYU,ID1,DATI,RNI,IBL1,IBL2)
C$C
C
C_____ SCRITTURA DEL FILE 14 CON I RISULTATI OTTENUTI DAL CALCOLO
C
C$C
      SCHEMA='####'
      DO 666 I = 1, 4
          IF ((ICHAR (SCHEMA(I:I)) .GT. 64) .AND. 
     $    (ICHAR (SCHEMA(I:I)) .LE. 90)) THEN
                 SCHLOW(I:I) = CHAR (ICHAR (SCHEMA(I:I)) + 32)
          ELSE
                 SCHLOW(I:I) = SCHEMA(I:I)
          ENDIF
  666 CONTINUE
C$C
      NOME_FILE14=SCHLOW//'_14.dat'
      OPEN(UNIT=2,FILE=NOME_FILE14,STATUS='UNKNOWN')
C     
C     ATTENZIONE:	   
C     in VMS aveva anche:
C       $     RECORDTYPE='VARIABLE',CARRIAGECONTROL='LIST')
C
C
      REWIND 14
C
      DO I=1,4
      READ(14,3000)LINE
      WRITE(2,3000)LINE
      ENDDO
3000  FORMAT(A)
C
      DO I=1,NU
      READ(14,3000)LINE
      IF(XYU(I).LT.0.) THEN
         WRITE(LINE(15:24),'(G10.4)')XYU(I)
      ELSE
         WRITE(LINE(15:24),'(G10.5)')XYU(I)
      ENDIF
      WRITE(2,3000)LINE
      ENDDO
C
   4  READ(14,3000,END=10)LINE
      WRITE(2,3000)LINE
      GO TO 4
C
  10  CLOSE(2)
      CLOSE(14)
C
C SCRITTURA FILE BINARIO SIMIL 04
      NOME_FILE04=SCHLOW//'_04.dat'
      OPEN(UNIT=4,FILE=NOME_FILE04,STATUS='UNKNOWN',FORM='UNFORMATTED')
      WRITE(4) NU, NI, NDATI
      WRITE(4) (LISTA(I), I=1, NU+NI)
      WRITE(4) (XYU(I), I=1, NU+NI)
      WRITE(4) (DATI(I), I=1, NDATI)
      CLOSE(4)
      STOP '  '
      END
