/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/* FILE DI INCLUDE PER FILES DI EDITING */

#include "szfiledf.inc"

#define mask 0100000
#define mask1 077777
	int fp1,fp2,head[512],headd[512],i,num;
