/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/* FILE DI INCLUDE DIMENSIONAMENTO FILES DI EDITING */

#define nmax 512
#define nblk 14
#define nrec 511
#define lnrec 6
#define ldes 7
#define lnsigle 10      /* lunghezza in byte della sigla   */

#define lun_nome 10
#define lun_ext  2
#define edf ".EDF"          /* estensione file di editing */
#define wsig_size 10        /* dimensione max delle sigle */

#define AA 0       /* tipi di punto esistenti */
#define AS 1
#define AC 2
#define AD 3
#define AO 4
#define DA 5
#define DS 6
#define DC 7
#define DD 8
#define DO 9
