/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/* ->SCHERMO.INC
 *	caratteristiche dello schermo
 */
#define xmax 80
#define ymax 24

/* attributi caratteri   */
#define off 0		/* bianco e nero normale	*/
#define hi  1           /* alta intensit…		*/
#define unds 4		/* underscore on		*/
#define blink 5		/* blink on			*/
#define reverse 7	/* reverse on			*/
#define	invis	8	/* invisibile			*/
#define	NERO 30		/* foreground nero		*/
#define	ROSSO 31 	/*	      rosso		*/
#define	VERDE 32  	/*            verde          	*/
#define	GIALLO 33  	/*	      giallo		*/
#define	MAGENTA 35  	/*	      magenta		*/
#define	CIANO 36  	/*	      ciano		*/
#define	BIANCO 37  	/*	      bianco		*/
#define	nero 40		/* background nero	   	*/
#define	rosso 41 	/*	      rosso		*/
#define	verde 42  	/*            verde          	*/
#define	giallo 43  	/*	      giallo		*/
#define	magenta 45  	/*	      magenta		*/
#define	ciano 46  	/*	      ciano		*/
#define	bianco 47  	/*	      bianco		*/

