int WINAPI WinMain(HANDLE, HANDLE, LPSTR, int);
BOOL InitApplication(HANDLE);
BOOL InitInstance(HANDLE, int);
LRESULT CALLBACK MainWndProc(HWND, unsigned, WPARAM, LPARAM);
BOOL CALLBACK About(HWND, unsigned, WPARAM, LPARAM);
int ReadHeaderF22(HWND);
int CALLBACK VariSel(HWND, unsigned, WPARAM, LPARAM);
void UpdateVariSel(HWND);
void compatstr();
int ReadF22(HWND);
int MinMaxDati();
void convReal();
int CALLBACK SetScale(HWND, unsigned, WPARAM, LPARAM);
void UpdateSetScale(HWND);
int CALLBACK MemoGroup(HWND, unsigned, WPARAM, LPARAM);
int CALLBACK RefrTime(HWND, unsigned, WPARAM, LPARAM);
int CALLBACK GroupSel(HWND, unsigned, WPARAM, LPARAM);
void UpdateGroupSel(HWND);
void AddGExt(PSTR, PSTR);
int ReadG22(HWND);
int WriteG22();
int DecodeCmdLine();
int lstrncmp(LPSTR, LPSTR, int);
HANDLE OpenGRFdlg();
