#!/bin/sh
#
#  Script:			run_make
#  Instance:		3
#  %version:		1 %
#  Description:		
#  %created_by:		famgr %
#  %date_created:	Tue Oct 15 17:16:31 1996 %
echo "Shell provvisoria per la compilazione ricorsiva"
if [ $# -eq 0 ]
then
        echo "inserire  flags tra apici"
else
OPTION=$1
echo "Sto per compilare"
echo "Flag usati: " $OPTION
cd ./procedure
ccm make $OPTION -f Makefile.mk
cd ..
cd ./tavole 
ccm make $OPTION -f Makefile.mk
cd ..
cd ./sorglego/sub
ccm make $OPTION -f Makefile.mk
cd ../main
ccm make $OPTION -f lego_main.mk
ccm make $OPTION -f cad_lego_main.mk
cd ../..
cd ./util
ccm make $OPTION -f Makefile.mk
cd ..
fi
