C**********************************************************************
C modulo amxi.f
C tipo 
C release 5.2
C data 4/12/95
C reserver @(#)amxi.f	5.2
C**********************************************************************
C
      SUBROUTINE AMXII3(IFO,IOB,DEBL)
C*****************************************************************************
C
C        BLOCCO MINIMO/MASSIMO DI DUE SEGNALI
C
C*****************************************************************************
C
C      IMPLICIT DOUBLE PRECISION (A-H, O-Z)                              !DBLE
      COMMON/AMXI01/IBLOC
      COMMON/AMXI02/NCEL,NPAR
      CHARACTER*80 DEBL
      CHARACTER*8 IBLOC
      CHARACTER*4 IOB
      CHARACTER*4 MOD
      DATA MOD/'AMXI'/
C
      CALL AMXII4(IOB,MOD)
      NSTATI = 0
      NUSCIT = 1
      NINGRE = 2
C
      WRITE(IFO,2999)IBLOC,IOB,MOD,DEBL
 2999 FORMAT(A,2X,'BL.-',A4,'- **** MODULO ',A4,' - ',A)
C
      WRITE(IFO,3001)IOB
 3001 FORMAT('UMXI',A4,2X,
     & '--UA-- OUTPUT ANALOG SIGNAL MIN/MAX')
      WRITE(IFO,3003)IOB
 3003 FORMAT('I1MX',A4,2X,
     & '--IN-- INPUT SIGNAL ONE TO MIN/MAX')
      WRITE(IFO,3004)IOB
 3004 FORMAT('I2MX',A4,2X,
     & '--IN-- INPUT SIGNAL TWO TO MIN/MAX')
C
      RETURN
      END
      SUBROUTINE AMXII4(IOB,MOD)
C      IMPLICIT DOUBLE PRECISION (A-H, O-Z)                              !DBLE
      COMMON/AMXI01/IBLOC
      COMMON/AMXI02/NCEL,NPAR
      CHARACTER*8 IBLOC
      CHARACTER*4 IOB
      CHARACTER*4 MOD
C
      WRITE(IBLOC,1000)MOD,IOB
 1000 FORMAT(2A4)
      RETURN
      END
      SUBROUTINE AMXII2(IFUN,VAR,MX1,IV1,IV2,XYU,DATI,ID1,ID2,
     &  IBL1,IBL2,IER,CNXYU,TOL)
C      IMPLICIT DOUBLE PRECISION (A-H, O-Z)                              !DBLE
      INTEGER VAR
      DIMENSION VAR(MX1,*),XYU(*),DATI(*),CNXYU(*),TOL(*)
      CHARACTER*10 AMX
C*******************************************
C
C____ AMXI - BLOCCO MIN/MAX DI DUE SEGNALI
C
C*********** INIZIO ISTRUZIONI ESECUTIVE
C
      GO TO(100,200), IFUN
 100  CONTINUE
      WRITE(14,3000)
 3000 FORMAT('    MIN/MAX  =',10X,'*')
      RETURN
C
C____ LETTURA DA FILE14 DEL NOME DEL BLOCCO
C
  200 READ(14,1000)
 1000 FORMAT(A)
C
      READ(14,1001)AMX
 1001 FORMAT(14X,A10)
      IF(AMX.EQ.'MAX') THEN
      WRITE(6,3001)IBL1,IBL2
 3001 FORMAT(/10X,'THE BLOCK ',2A4,' MAKES TWO SIGNALS MAXIMUM')
C     FA IL MASSIMO DI DUE SEGNALI')
      DATI(ID1)=1.
      ELSE
      WRITE(6,3002)IBL1,IBL2
 3002 FORMAT(/10X,'THE BLOCK ',2A4,' MAKES TWO SIGNALS MINIMUM')
C     FA IL MINIMO DI DUE SEGNALI')
      DATI(ID1)=0.
      ENDIF
C
      ID2=ID1
C
C____ COSTANTI DI NORMALIZZAZIONE
C
      CNXYU(IV1 )=1.
      CNXYU(IV1+1)=1.
      CNXYU(IV1+2)=1.
C
C____ TOLLERANZE 1 PER MILLE
C
      TOL(1)=1.E-3
C
      RETURN
      END
      SUBROUTINE AMXIC1(IFUN,AJAC,MX5,IXYU,XYU,IPD,DATI,RNI,IBL1,IBL2)
C      IMPLICIT DOUBLE PRECISION (A-H, O-Z)                              !DBLE
      DIMENSION AJAC(MX5,*),XYU(*),DATI(*),RNI(*)
      LOGICAL KREGIM,J1,JFLOLOG
      COMMON/REGIME/KREGIM
      COMMON/INTEGR/TSTOP,TEMPO,DTINT,NPAS,CDT                          !SNGL
C      COMMON/INTEG1/TSTOP,TEMPO,DTINT,CDT,ALFADT,NPAS                   !DBLE
      COMMON/PARPAR/NUL(7),ITERT
C*******************************************
C
C____ AMXI - MIN/MAX DI DUE SEGNALI
C
C*********** INIZIO ISTRUZIONI ESECUTIVE
C
      GO TO (1,100,2),IFUN
C
C____ TOPOLOGIA JACOBIANO
C
 1    AJAC(1,1)=1.
      AJAC(1,2)=1.
      AJAC(1,3)=1.
      RETURN
C
C____ COEFFICIENTI JACOBIANO
C
 2    CONTINUE
      UU = XYU(IXYU +  0)
      E1 = XYU(IXYU +  1)
      E2 = XYU(IXYU +  2)
      J1 = JFLOLOG( DATI(IPD) )
C
      IF(J1) THEN
C____ MASSIMO DEI DUE SEGNALI
	IF(E2.GE.E1)GO TO 11
	GO TO 31
      ELSE
C____ MINIMO DEI DUE SEGNALI
	IF(E2.LE.E1)GO TO 11
	GO TO 31
      ENDIF
C ! E2
 11     AJAC(1,3)=1.
	GO TO 51
C ! E1
 31     AJAC(1,2)=1.
C
 51     AJAC(1,1)=-1.
      RETURN
C
C____ CALCOLO DELLA RISPOSTA DEI REGOLATORI
C
 100  CONTINUE
C
C____ DECODIFICA DELLE VARIABILI
C
      UU = XYU(IXYU +  0)
      E1 = XYU(IXYU +  1)
      E2 = XYU(IXYU +  2)
      J1 = JFLOLOG( DATI(IPD) )
C
      IF(J1) THEN
C____ MASSIMO DEI DUE SEGNALI
	IF(E2.GE.E1) GO TO 10
	GO TO 30
      ELSE
C____ MINIMO DEI DUE SEGNALI
	IF(E2.LE.E1) GO TO 10
	GO TO 30
      ENDIF
 10     EE = E2
	GO TO 50
 30     EE = E1
 50     RNI(1) = UU - EE
      RETURN
      END
CC
      SUBROUTINE AMXID1(BLOCCO,NEQUAZ,NSTATI,NUSCIT,NINGRE,SYMVAR,XYU,
     $   IXYU,DATI,IPD,SIGNEQ,UNITEQ,COSNOR,ITOPVA,MXT)
      RETURN
      END
