C**********************************************************************
C modulo ljun.f
C tipo 
C release 5.2
C data 4/12/95
C reserver @(#)ljun.f	5.2
C***********************************************************************
C
      SUBROUTINE LJUNI2(IFUN,VAR,MX1,IV1,IV2,XYU,DATI,ID1,ID2,
     $   NOMBL1,NOMBL2,IER,CNXYU,TOL)
C
C      IMPLICIT DOUBLE PRECISION (A-H, O-Z)                              !DBLE
      INTEGER VAR
      DIMENSION VAR(MX1,*),XYU(*),DATI(*),CNXYU(*),TOL(*)
      COMMON/NORM/P0,H0,T0,W0,RO0,AL0,V0,DP0
      CHARACTER*4 NVM,NAS,NRA,NLAM,ISPA,NALI,NLUN,NRO,NCM
      DATA NCM,NRO,NVM,NAS,NRA/'CM','ROM','VMET','ASCA','RALJ'/
      DATA NLAM,ISPA/'ALAM','    '/,NALI/'ALIB'/,NLUN/'LUNG'/
C
      GOTO(1,10),IFUN
C
C--------SCRITTURA SIMBOLI DATI
C
1     WRITE(14,101)NCM,ISPA,NRO,ISPA
      WRITE(14,101)NVM,ISPA,NAS,ISPA,NRA,ISPA
      WRITE(14,101)NLUN,ISPA,NLAM,ISPA,NALI,ISPA
101   FORMAT(3(4X,2A4,' =',10X,'*'),5X)
      RETURN
C
C------------LETTURA DATI DA FILE 14
C
10    READ(14,102)
      READ(14,102)CM,ROM
      READ(14,102)VMET,ASCA,RALJ
      READ(14,102)ALUN,ALAM,ALIB
102   FORMAT(3(14X,F10.2,1X),5X)
C
C------------MEMORIZZAZIONE NEL VETTORE DATI
C
	NCEL=((IV2-IV1)-5)/4
      ALFA=6.28/NCEL
      AS=ASCA/NCEL
      VS=VMET/NCEL
      PER=ASCA/ALUN
      DIAI=ALIB/PER
C
C------------INGRESSI FITTIZI
C
CC    CALL MULTINI2(VAR,MX1,IV1,IV2,DATI,ID1,ID2)
C
      DATI(ID2)=CM
      DATI(ID2+1)=ROM
      DATI(ID2+2)=VS
      DATI(ID2+3)=AS
      DATI(ID2+4)=ALFA
      DATI(ID2+5)=DIAI
      DATI(ID2+6)=ALAM
      DATI(ID2+7)=ALIB
      DATI(ID2+8)=NCEL
C
      ID2=ID2+8
C
C----------COSTANTI DI NORMALIZZAZIONE
C
      I1=IV1
      I2=I1+3*NCEL+1
      DO 2 I=I1,I2
      CNXYU(I)=T0
2     CONTINUE
C
      CNXYU(I2+1)=W0
      CNXYU(I2+2)=W0
      I1=I2+2
      DO 3 I=I1+1,I1+NCEL
      CNXYU(I)=T0
3     CONTINUE
      CNXYU(I1+NCEL+1)=1.
      CNXYU(I1+NCEL+2)=1.
C
      RETURN
      END
C
C
C******************************************************************
C
      SUBROUTINE LJUNC1(IFUN,AJAC,MX5,IXYU,XYU,IPD,DATI,RN,
     $   IBLOC1,IBLOC2)
C      IMPLICIT DOUBLE PRECISION (A-H, O-Z)                              !DBLE
      LOGICAL KREGIM
      DIMENSION TMM(12),TM(12),T(12),GAM(12),H(12),DHDT(12)
      DIMENSION DGADTM(12),DGADT(12),DGADTA(12),DGADTF(12)
      DIMENSION DGADWF(12),DGADWA(12),TF(12),TA(12)
      DIMENSION AJAC(MX5,*),XYU(*),DATI(*),RN(*)
      DIMENSION HF(12),HA(12),DHDTF(12),DHDTA(12)
      COMMON/NORM/P0,H0,T0,W0,RO0,AL0,V0,DP0
      COMMON/REGIME/KREGIM
C
	NIPD=IPD
      NCEL=DATI(NIPD+8)
C
      GOTO(1,20,20),IFUN
C
C------------TOPOLOGIA MATRICE JACOBIANA---------------
C
1     DO 13 I=1,NCEL
      AJAC(I,I)=1.
      AJAC(I,2*NCEL+I)=1.
      AJAC(I,4*NCEL+5)=1.
C
      AJAC(NCEL+I,I)=1.
      AJAC(2*NCEL+I,I)=1.
      AJAC(2*NCEL+I,2*NCEL+I)=1.
C
13    CONTINUE
C
      AJAC(1,NCEL+1)=1.
      AJAC(1,2*NCEL)=1.
      AJAC(NCEL+1,NCEL+1)=1.
      AJAC(NCEL+1,2*NCEL)=1.
C
      DO 12 I=2,NCEL
      AJAC(I,NCEL-1+I)=1.
      AJAC(I,NCEL+I)=1.
      AJAC(NCEL+I,NCEL-1+I)=1.
      AJAC(NCEL+I,NCEL+I)=1.
C
12    CONTINUE
C
      DO 14 I=1,.5*NCEL
      AJAC(I,3*NCEL+3)=1.
      AJAC(I,3*NCEL+4+I)=1.
C
      AJAC(2*NCEL+I,3*NCEL+3)=1.
      AJAC(2*NCEL+I,3*NCEL+4+I)=1.
C
      AJAC(3*NCEL+1,2*NCEL+I)=1.
C
14    CONTINUE
C
      DO 15 I=.5*NCEL+1,NCEL
      AJAC(I,3*NCEL+4)=1.
      AJAC(I,3*NCEL+4+I)=1.
C
      AJAC(2*NCEL+I,3*NCEL+4)=1.
      AJAC(2*NCEL+I,3*NCEL+4+I)=1.
C
      AJAC(3*NCEL+2,2*NCEL+I)=1.
C
15    CONTINUE
C
      DO 16 I=1,NCEL
      AJAC(I,4*NCEL+6)=1.
      AJAC(2*NCEL+I,4*NCEL+6)=1.
16    CONTINUE
      AJAC(3*NCEL+1,3*NCEL+1)=1.
      AJAC(3*NCEL+2,3*NCEL+2)=1.
CC    CALL MULTINC1(IFUN,AJAC,MX5,IXYU,XYU,IPD,DATI)
      RETURN
C
C--------------DECODIFICA DATI---------
C
20    NIPD=IPD
      CM=DATI(NIPD)
      ROM=DATI(NIPD+1)
      VS=DATI(NIPD+2)
      AS=DATI(NIPD+3)
      ALFA=DATI(NIPD+4)
      DIAI=DATI(NIPD+5)
      ALAM=DATI(NIPD+6)
      ALIB=DATI(NIPD+7)
      NCEL=DATI(NIPD+8)
C
      CM=CM*ROM*VS
C
C----------------DECODIFICA VARIABILI--------
C
CC    CALL MULTINC1(2,AJAC,MX5,IXYU,XYU,IPD,DATI)
      DO 11 J=1,NCEL
      TMM(J)=XYU(IXYU+J-1)*T0
      TM(J)=XYU(IXYU+NCEL+J-1)*T0
      T(J)=XYU(IXYU+2*NCEL+J-1)*T0
C
11    CONTINUE
C
      TFU=XYU(IXYU+3*NCEL)*T0
      TAU=XYU(IXYU+3*NCEL+1)*T0
      WF=XYU(IXYU+3*NCEL+2)*W0
      WA=XYU(IXYU+3*NCEL+3)*W0
      I1=IXYU+3*NCEL+3
      I2=I1+.5*NCEL
      DO 4 I=1,.5*NCEL
      TF(I)=XYU(I1+I)*T0
4     CONTINUE
      DO 3 I=1,.5*NCEL
      TA(I)=XYU(I2+I)*T0
3     CONTINUE
      OMLJ=XYU(IXYU+4*NCEL+4)*1.
      CSCA=XYU(IXYU+4*NCEL+5)
C
C-----------CALCOLO ENTALPIE E CALORI SPECIFICI--------
C
      DO 2 I=1,.5*NCEL
      HF(I)=HTFU(TF(I),.1,1)
      HA(I)=HTFU(TA(I),.1,1)
      DHDTF(I)=CPFU(TF(I),.1)
      DHDTA(I)=CPFU(TA(I),.1)
2     CONTINUE
C
      DO 10 I=1,NCEL
      H(I)=HTFU(T(I),.1,1)
      DHDT(I)=CPFU(T(I),.1)
10    CONTINUE
C
C-------------CALCOLO VETTORE GAM E SUE DERIVATE----------
C
      CALL GAMMA(TMM,T,TF,TA,WF,WA,ALIB,DIAI,NCEL
     $  ,GAM,DGADTM,DGADT,DGADTF,DGADTA,DGADWF,DGADWA)
C
C
C     WRITE(6,*)'GAMMA=',GAM
      IF(IFUN.EQ.3)GOTO 50
C
C----------CALCOLO RESIDUI PRIMA CELLA
C
C
C CALCOLO CON PORTATE NULLE O NEGATIVE
C
	WX=W0*1.E-2
      IF((WF.LT.WX).OR.(WA.LT.WX)) THEN
      DO I=1,3*NCEL+2
      RN(I)=0.
      END DO
      RETURN
      ENDIF
C
      RN(1)=OMLJ/ALFA*(TM(NCEL)-TM(1))+CSCA*GAM(1)*AS/CM*
     $  (ALAM*TF(1)+(1-ALAM)*T(1)-TMM(1))
      RN(NCEL+1)=-TMM(1)+ALAM*TM(NCEL)+(1-ALAM)*TM(1)
      RN(2*NCEL+1)=-CSCA*GAM(1)*AS/ALFA*(ALAM*TF(1)+(1-ALAM)*T(1)
     $   -TMM(1))+WF/(.5*NCEL*ALFA)*(HF(1)-H(1))
C
C-----------NORMALIZZAZIONE RESIDUI PRIMA CELLA
C
      RN(1)=RN(1)/T0
      RN(NCEL+1)=RN(NCEL+1)/T0
      RN(2*NCEL+1)=RN(2*NCEL+1)/(W0*H0)
C
C-----------CALCOLO RESIDUI CELLE 2-NCEL------
C
      DO 9 I=2,NCEL
      IF(I.GT..5*NCEL)GOTO 8
C------------------PARTE FUMI----------
C
      TMF=ALAM*TF(I)+(1-ALAM)*T(I)
      W1=WF/(.5*NCEL)
      H1=HF(I)
      GOTO 7
C                                   PARTE ARIA
8     TMF=ALAM*TA(INT(I-.5*NCEL))+(1-ALAM)*T(I)
      W1=WA/(.5*NCEL)
      H1=HA(INT(I-.5*NCEL))
C
7     RN(I)=OMLJ/ALFA*(TM(I-1)-TM(I))+CSCA*GAM(I)*AS/CM*(TMF-TMM(I))
      RN(NCEL+I)=-TMM(I)+ALAM*TM(I-1)+(1-ALAM)*TM(I)
      RN(2*NCEL+I)=-CSCA*GAM(I)*AS/ALFA*(TMF-TMM(I))+W1/ALFA*(H1-H(I))
C
C-------------NORMALIZZAZIONE RESIDUI 2-NCEL
C
      RN(I)=RN(I)/T0
      RN(NCEL+I)=RN(NCEL+I)/T0
      RN(2*NCEL+I)=RN(2*NCEL+I)/(W0*H0)
9     CONTINUE
C
C----------------RESIDUI T_FUMI-USCITA  T_ARIA-USCITA
C
      TFUM=0.
      DO 6 I=1,.5*NCEL
      TFUM=TFUM+T(I)/(.5*NCEL)
6     CONTINUE
C
      TAR=0.
      DO 5 I=.5*NCEL+1,NCEL
      TAR=TAR+T(I)/(.5*NCEL)
5     CONTINUE
C
      RN(3*NCEL+1)=-TFU+TFUM
      RN(3*NCEL+2)=-TAU+TAR
C
C-----NORMALIZZAZIONE
C
      RN(3*NCEL+1)=RN(3*NCEL+1)/T0
      RN(3*NCEL+2)=RN(3*NCEL+2)/T0
C
      RETURN
C
C*******************CALCOLO DELLO JACOBIANO*************
C
  50    CONTINUE
C
C  JACOBIANO CON PORTATE NULLE O NEGATIVE
	WX=W0*1.E-2
      IF((WF.LT.WX).OR.(WA.LT.WX)) THEN
      DO I=1,3*NCEL+2
      AJAC(I,I)=1.
      END DO
      RETURN
      END IF
C
C------------DERIVATE RISPETTO AGLI STATI-------
C
      DO 100 I=1,NCEL
      IF(I.GT..5*NCEL) GOTO 51
      TMF=ALAM*TF(I)+(1-ALAM)*T(I)
      GOTO 52
51    TMF=ALAM*TA(INT(I-.5*NCEL))+(1-ALAM)*T(I)
52    DFDGAM=CSCA*AS/CM*(TMF-TMM(I))
      F11=DFDGAM*DGADTM(I)
      AJAC(I,I)=-GAM(I)*CSCA*AS/CM+F11
      AJAC(NCEL+I,I)=1.
      DG2DGAM=CSCA*AS/ALFA*(TMF-TMM(I))
      G21=DG2DGAM*DGADTM(I)
      AJAC(2*NCEL+I,I)=(-GAM(I)*CSCA*AS/ALFA+G21)*T0/(W0*H0)
C
C-------------DERIVATE RISPETTO ALLE TEMPERATURE USCITA_FUMI-ARIA
C
      F13=DFDGAM*DGADT(I)
      AJAC(I,2*NCEL+I)=GAM(I)*CSCA*AS/CM*(1-ALAM)+F13
      IF(I.GT..5*NCEL) GOTO 53
      W=WF/(.5*NCEL)
      GOTO 54
53    W=WA/(.5*NCEL)
54    G23=DG2DGAM*DGADT(I)
      AJAC(2*NCEL+I,2*NCEL+I)=(GAM(I)*CSCA*AS/ALFA*(1-ALAM)+G23+
     $    W/ALFA*DHDT(I))*T0/(W0*H0)
100   CONTINUE
C
C---------------DERIVATE RISPETTO ALLA TEMPERATURA METALLO
C
      AJAC(1,NCEL+1)=-OMLJ/ALFA
      AJAC(1,2*NCEL)=OMLJ/ALFA
C
      DO 101 I=2,NCEL
      AJAC(I,NCEL-1+I)=OMLJ/ALFA
      AJAC(I,NCEL+I)=-OMLJ/ALFA
C
      AJAC(NCEL+I,NCEL-1+I)=-ALAM
      AJAC(NCEL+I,NCEL+I)=-(1-ALAM)
101   CONTINUE
      AJAC(NCEL+1,NCEL+1)=-(1-ALAM)
      AJAC(NCEL+1,2*NCEL)=-ALAM
C
C---------DERIVATE DELLE T_USCITA FUMI-ARIA RISPETTO ALLE T(I)
C
      DO 102 I=1,.5*NCEL
      AJAC(3*NCEL+1,2*NCEL+I)=-1/(.5*NCEL)
102   CONTINUE
      DO 103 I=.5*NCEL+1,NCEL
      AJAC(3*NCEL+2,2*NCEL+I)=-1/(.5*NCEL)
103   CONTINUE
C
C---------DERIVATE RISPETTO ALLA T-FUMI-USCITA  T_ARIA-USCITA
C
      AJAC(3*NCEL+1,3*NCEL+1)=1.
      AJAC(3*NCEL+2,3*NCEL+2)=1.
C
C-------------DERIVATE RISPETTO ALLA PORTATA FUMI
C
      DO 104 I=1,.5*NCEL
      TMF=ALAM*TF(I)+(1-ALAM)*T(I)
      AJAC(I,3*NCEL+3)=(AS*CSCA/CM*(TMF-TMM(I))*DGADWF(I))*W0/T0
      AJAC(2*NCEL+I,3*NCEL+3)=(DGADWF(I)*CSCA*AS/ALFA*(TMF-TMM(I))-
     $   (HF(I)-H(I))/(.5*NCEL*ALFA))/H0
104   CONTINUE
C
C---------------DERIVATE RISPETTO ALLA PORTATA ARIA
C
      DO 105 I=.5*NCEL+1,NCEL
      TMA=ALAM*TA(INT(I-.5*NCEL))+(1-ALAM)*T(I)
      AJAC(I,3*NCEL+4)=(AS*CSCA/CM*(TMA-TMM(I))*DGADWA(I))*W0/T0
      AJAC(2*NCEL+I,3*NCEL+4)=(DGADWA(I)*CSCA*AS/ALFA*(TMA-TMM(I))-
     $    (HA(INT(I-.5*NCEL))-H(I))/(.5*NCEL*ALFA))/H0
105   CONTINUE
C
C----------------DERIVATE RISPETTO ALLA T_FUMI -INGRESSO
C
      DO 106 I=1,.5*NCEL
      TMF=ALAM*TF(I)+(1-ALAM)*T(I)
      DFDGAM=AS*CSCA/CM*(TMF-TMM(I))
      F15=DFDGAM*DGADTF(I)
      AJAC(I,3*NCEL+4+I)=GAM(I)*CSCA*AS/CM*ALAM+F15
C
      W=WF/(.5*NCEL)
      DG2DGAM=AS*CSCA/ALFA*(TMF-TMM(I))
      G25=DG2DGAM*DGADTF(I)
      AJAC(2*NCEL+I,3*NCEL+4+I)=(GAM(I)*CSCA*AS/ALFA*ALAM-W/ALFA*DHDTF
     $   (I)+G25)*T0/(W0*H0)
106   CONTINUE
C
C-----------------DERIVATE RISPETTO ALLA T_ARIA-INGRESSO
C
      DO 107 I=.5*NCEL+1,NCEL
      TMA=ALAM*TA(INT(I-.5*NCEL))+(1-ALAM)*T(I)
      DFDGAM=AS/CM*(TMA-TMM(I))
      F15=DFDGAM*DGADTA(I)
      AJAC(I,3*NCEL+4+I)=GAM(I)*CSCA*AS/CM*ALAM+F15
C
      W=WA/(.5*NCEL)
      DG2DGAM=AS*CSCA/ALFA*(TMA-TMM(I))
      G25=DG2DGAM*DGADTA(I)
      AJAC(2*NCEL+I,3*NCEL+4+I)=(GAM(I)*CSCA*AS/ALFA*ALAM-W/ALFA
     $   *DHDTA(INT(I-.5*NCEL))+G25)*T0/(W0*H0)
107   CONTINUE
C
C------------------DERIVATE RISPETTO ALLA VELOCITA OMLJ
C
      DO 108 I=2,NCEL
      AJAC(I,4*NCEL+5)=-(TM(I)-TM(I-1))/ALFA/T0
108   CONTINUE
      AJAC(1,4*NCEL+5)=-(TM(1)-TM(NCEL))/ALFA/T0
C
C-----------DERIVATE RISPETTO A CSCA
C     DO 109 I=1,.5*NCEL
      AJAC(I,4*NCEL+6)=(GAM(I)*AS/CM*(ALAM*TF(I)+(1-ALAM)*T(I)
     $  -TMM(I)))/T0
      AJAC(2*NCEL+I,4*NCEL+6)=AJAC(I,4*NCEL+6)*CM/ALFA*T0/(W0*H0)
109   CONTINUE
      DO 110 I=.5*NCEL+1,NCEL
      TMF=ALAM*TA(INT(I-.5*NCEL))+(1-ALAM)*T(I)
      AJAC(I,4*NCEL+6)=(GAM(I)*AS/CM*(TMF-TMM(I)))/T0
      AJAC(2*NCEL+I,4*NCEL+6)=AJAC(I,4*NCEL+6)*CM/ALFA*T0/(W0*H0)
110   CONTINUE
CC    CALL MULTINC1(IFUN,AJAC,MX5,IXYU,XYU,IPD,DATI)
      RETURN
      END
C
C
C**************SUBROUTINE PER IL CALCOLO DEL COEFFICIENTE DI SCAMBIO****
C                         E SUE DERIVATE
C
C
      SUBROUTINE GAMMA(TMM,T,TF,TA,WF,WA,ALIB,DIAI,NCEL,GAM,
     $  DGADTM,DGADT,DGADTF,DGADTA,DGADWF,DGADWA)
C
C      IMPLICIT DOUBLE PRECISION (A-H, O-Z)                              !DBLE
      DIMENSION TMM(*),T(*),GAM(*),DGADTM(*),DGADT(*),TF(*),TA(*)
      DIMENSION DGADTF(*),DGADTA(*),DGADWF(*),DGADWA(*)
      DATA EPS/1.E-5/
      DO 2 I=1,NCEL
      IF(I.GT..5*NCEL)GOTO 10
C
C !CASO FUMI
      A=123.2
      B=105.7E-3
      C=-27.3E-6
      T1=TF(I)
      G=ABS(WF/(.5*ALIB))
      GOTO 20
C ALIB RAPPRESENTA L'AREA TRASVERSALE LIBERA TOTALE
C !CASO ARIA
10    A=122.4
      B=87.4E-3
      C=-17.85E-6
      T1=TA(INT(I-.5*NCEL))
      G=ABS(WA/(.5*ALIB))
C
20    TM=.5*(T1+T(I))
      TFLM=.5*(TMM(I)+TM)
      FPP=A+(B+C*TFLM)*TFLM
      FT=(ABS(TMM(I)/TFLM))**.8
C                                 CALCOLO DI GAMMA
      GAM(I)=.023*(G+EPS)**.8*FPP*FT/(DIAI**.2)
      DGADW=.8*GAM(I)/(.5*ALIB*(G+EPS))
      IF(I.GT..5*NCEL) DGADWA(I)=DGADW
      DGADWF(I)=DGADW
C
      DGADFP=GAM(I)/FPP
      DGADFT=GAM(I)/FT
      DFPDTFLM=B+2*C*TFLM
      DTFLMDTM=.5
      DFPDTM=.5*DFPDTFLM
C
C     DFTDTM=.8*(TMM(I)/TFLM)**(-.2)*(TFLM-.5*TMM(I))/(TFLM*TFLM)
      DFTDTM=0.8/(2*TMM(I))
      DTFLMDT=.25
      DTFLMDT1=DTFLMDT
      DFPDT=DFPDTFLM*.25
      DFPDT1=DFPDT
C     DFTDT=-.8*(TMM(I)/TFLM)**(-.2)*.25/(TFLM*TFLM)
      DFTDT=-DFTDTM
C
      DGADTM(I)=DGADFP*DFPDTM+DGADFT*DFTDTM
      DGADT(I)=DGADFP*DFPDT+DGADFT*DFTDT
C
      IF(I.GT..5*NCEL) GOTO 3
      DGADTF(I)=DGADT(I)
      GOTO 2
3     DGADTA(I)=DGADT(I)
2     CONTINUE
      RETURN
      END
C*********************************************************************
      SUBROUTINE LJUNI3(IFO,IOB,DEBL)
C
C      IMPLICIT DOUBLE PRECISION (A-H, O-Z)                              !DBLE
      COMMON/LJUN01/IBLOC
      COMMON/LJUN02/NCEL,NPAR
      CHARACTER*80 DEBL
      CHARACTER*8 IBLOC
      CHARACTER*4 IOB
      CHARACTER*4 MOD
      DATA MOD/'LJUN'/
C
      CALL LJUNI4(IOB,MOD)
C
C
C     DEFINISCE NUMERO STATI-USCITE-INGRESSI
C
      NSTATI=NCEL
      NUSCIT=NCEL*2+2
      NINGRE=NCEL+4
C
C       NSTATI = 4
C       NUSCIT = 10
C       NINGRE = 8
C
      WRITE(IFO,2999)IBLOC,IOB,MOD,DEBL
 2999 FORMAT(A,2X,'BL.-',A4,'- **** MODULO ',A4,' - ',A)
C
      DO I=1,NCEL
      WRITE(IFO,3001)I,IOB,I
 3001 FORMAT('TM',I2,A4,2X,
     $  '--US-- MEAN METAL TEMPERATURE OF THE CELL ',I2)
      ENDDO
C
      DO I=1,NCEL
      WRITE(IFO,3002)I,IOB,I
 3002 FORMAT('TU',I2,A4,2X,
     $  '--UA-- METAL TEMPERATURE AT THE CELL ',I2,' OUTLET')
      ENDDO
C
      DO I=1,NCEL
       IF(I.LE..5*NCEL) THEN
	 WRITE(IFO,3003)I,IOB,I
 3003 FORMAT('TF',I2,A4,2X,
     $  '--UA-- FLUE GAS TEMPERATURE AT CELL ',I2,' OUTLET')
      ELSE
      WRITE(IFO,3004)I,IOB,I
 3004 FORMAT('TA',I2,A4,2X,
     $  '--UA-- AIR TEMPERATURE AT CELL ',I2,' OUTLET')
       ENDIF
      ENDDO
C
      WRITE(IFO,3005)IOB
 3005 FORMAT('TFUL',A4,2X,
     $  '--UA-- FLUE GAS TEMPERATURE AT THE LJUNGSTROEM OUTLET')
      WRITE(IFO,3006)IOB
 3006 FORMAT('TAUL',A4,2X,
     $  '--UA-- AIR TEMPERATURE AT THE LJUNGSTROEM OUTLET')
C
C--INGRESSI...
C
      WRITE(IFO,3007)IOB
 3007 FORMAT('WFLJ',A4,2X,
     $  '--IN-- FLUE GAS FLOW RATE INTO THE LJUNGSTROEM')
      WRITE(IFO,3008)IOB
 3008 FORMAT('WALJ',A4,2X,
     $  '--IN-- AIR FLOW RATE INTO THE LJUNGSTROEM')
C
       DO I=1,NCEL
       IF(I.LE..5*NCEL) THEN
	 WRITE(IFO,3010)I,IOB,I
 3010    FORMAT('TG',I2,A4,2X,
     $   '--IN-- FLUE GAS TEMPERATURE AT THE CELL ',I2,' INLET')
      ELSE
	 WRITE(IFO,3011)I,IOB,I
 3011    FORMAT('TI',I2,A4,2X,
     $   '--IN-- AIR TEMPERATURE AT THE CELL ',I2,' INLET')
      ENDIF
      ENDDO
C
      WRITE(IFO,3012)IOB
 3012 FORMAT('OMLJ',A4,2X,
     $  '--IN-- ROTATIONAL SPEED OF THE LJUNGSTROEM')
      WRITE(IFO,3013)IOB
 3013 FORMAT('CSCA',A4,2X,
     $  '--IN-- CORR. FACTOR OF THERMAL EXCHANGE COEFFICENT')
       RETURN
       END
C*********************************************************************
      SUBROUTINE LJUNI4(IOB,MOD)
C      IMPLICIT DOUBLE PRECISION (A-H, O-Z)                              !DBLE
      COMMON/LJUN01/IBLOC
      COMMON/LJUN02/NCEL,NPAR
      CHARACTER*8 IBLOC
      CHARACTER*4 IOB
      CHARACTER*4 MOD
C
C
      WRITE(IBLOC,1000)MOD,IOB
 1000 FORMAT(2A4)
1     WRITE(6,2000)
 2000 FORMAT(//,10X,'LJUNGSTROEM - NUMBER AZIMUTHAL CELLS (02-12)')
      READ(5,*)NCEL
      IF(NCEL.LT.2.OR.NCEL.GT.12) THEN
	WRITE(6,101)
 101    FORMAT(1X,'*** WRONG NUMBER OF CELLS! ***')
	GOTO 1
       ENDIF
C
C--CONTROLLO SE NCEL E` PARI
       IM=NCEL/2
       IM=NCEL-IM*2
       IF(IM.NE.0) THEN
	 WRITE(6,102)
 102     FORMAT(1X,'*** THE NUMBER OF CELLS MUST BE EVEN! ***')
	 GOTO 1
       ENDIF
       RETURN
       END
CC
      SUBROUTINE LJUND1(BLOCCO,NEQUAZ,NSTATI,NUSCIT,NINGRE,SYMVAR,
     $   XYU,IXYU,DATI,IPD,SIGNEQ,UNITEQ,COSNOR,ITOPVA,MXT)
      RETURN
      END
