/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
;**********************************************************
;
;	dimensionamenti code 
;
;**********************************************************

DIM_CODA_PRN	EQU 2000		;coda  stampanti
DIM_CODA_KEYB	EQU 360			;coda  tastiere

