C*********************************************************************
C       Fortran Source:             lepert.f
C       Subsystem:              1
C       Description:
C       %created_by:    lomgr %
C       %date_created:  Tue Aug 21 10:27:10 2001 %
C
C**********************************************************************


C
C Procedura contenete la variabile per l'identificazione della versione
C
      BLOCK DATA BDD_lepert_f
      CHARACTER*80  RepoID
      COMMON /CM_lepert_f / RepoID
      DATA RepoID/'@(#)1,fsrc,lepert.f,2'/
      END
C**********************************************************************
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                      C
C           LEGO unificato per singola / doppia precisione             C
C                 e per diverse piattaforme operative                  C
C                                                                      C
C   Attivata versione singola precisione per sistema operativo Unix    C
C                                                                      C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE LEPERT(VARI,MX3,UU,NU,TSTEP,NPER,IVPER,ITPER,IPPER,
     $                  DATPER,MXPERT,CNUU,MXDPER)
      DIMENSION UU(*),IVPER(*),ITPER(*),IPPER(*),DATPER(*),CNUU(*)
      DIMENSION U(100),T(100),ITITOL(20)
      CHARACTER*8 VARI(MX3), VAVA
      CHARACTER *15 LEGCAR
 1500 FORMAT (A)
C
      COMMON/PARINT/ITITOL,TFIN,PS1,PS2,IPS4,PS3
C
      KP=0
      NPER=0
      WRITE(6,1016)
 1016 FORMAT(/10X,'NOTA 1: I TEMPI CHE DEFINISCONO LE PERTURBAZIONI'
     $,' AL SISTEMA'/18X,'DEVONO ESSERE MULTIPLI DEL PASSO DI '
     $,'INTEGRAZIONE'//)
      WRITE(6,2016)
 2016 FORMAT(/10X,'NOTA 2: NON SI PUO PERTURBARE PIU VOLTE LO '
     $,'STESSO INGRESSO'/18X,'TUTTE LE PERURBAZIONI SONO RIFERITE'
     $/18X,'AL VALORE INIZIALE DELL INGRESSO'
     $/18X,'SE IL MODULO DEL VALORE INIZIALE (MKS) < 1.E-5 '
     $,/18X,'OCCORRE ASSEGNARE UN VALORE DI RIFERIMENTO IN MKS.'//)
      IPPER(1)=0
    1 WRITE(6,1000)
 1000 FORMAT(///10X,'ASSEGNA IL NOME DELLA VARIABILE DI INGRESSO CHE',
     $   ' VUOI PERTURBARE '/)
      READ(5,1001) VAVA
 1001 FORMAT(A8)
      IF(VAVA .EQ. ' ')GO TO 100
      IF(VAVA .NE. '?')GO TO   9
    8 WRITE(6,2234)(VARI(I),I=1,NU)
 2234 FORMAT(//10X,'ELENCO DELLE VARIABILI DI INGRESSO'//(10(2X,A8)/))
      GO TO 1
    9 DO 10 I=1,NU
        IF(VAVA .EQ. VARI(I))GO TO 15
   10 CONTINUE
      WRITE(6,3000) VAVA
 3000 FORMAT(10X,'ER - LA VARIABILE ',A8,
     $   ' NON ESISTE FRA GLI INGRESSI')
      GO TO 8
   15 IPV=I
C
C****CONTROLLO CHE LA VARIABILE NON SIA STATA GIA PERTURBATA
C
      IF(NPER.EQ.0)GO TO 550
      DO 500 I=1,NPER
      IF(IVPER(I).EQ.IPV)GOTO 510
  500 CONTINUE
      GO TO 550
  510 WRITE(6,3016)VAVA
 3016 FORMAT(5X,'VARIABILE ',A8, ' GIA PERTURBATA')
      GO TO 1
C
  550 CNU0=CNUU(IPV)
      CU0=UU(IPV)
      UU0=CU0
      RUU0=UU0*CNU0
      WRITE(6,2012)VAVA,RUU0
 2012 FORMAT(/5X,'VALORE DI ',A8,2X,E12.5,' (MKS)'/)
      IF(ABS(RUU0).GT.1.E-5)GO TO 20
      WRITE(6,1012)VAVA
 1012 FORMAT(/5X,'VALORE DI ',A8,2X,
     $   'UGUALE A ZERO'/5X,'ASSEGNA UN VALORE NUOVO (MKS)'
     $   /5X,'A CUI VERRA RIFERITA LA PERTURBAZIONE')
      READ(5,*)UU00
      UU0=UU00/CNU0
 1101 FORMAT(F15.0)
 1102 FORMAT(I1)
   20 CONTINUE
   21 WRITE(6,1002)
 1002 FORMAT(10X,'TIPO DI PERTURBAZIONE?'
     $   /10X,'(RAMPA=1,TABULAZIONE=2,GRADINO=3)')
      READ(5,*)ITPR
      IF(ITPR.LT.1)GO TO 21
      IF(ITPR.GT.3)GO TO 21
C
      GO TO (22,50,90),ITPR
C
   22 WRITE(6,1003)
 1003 FORMAT(10X,'ASSEGNA -T1(INIZ.),T2(FIN.),U(T2) = Ur(T2)/U(0)  '/)
      READ(5,*) T1,T2,UMAX
      IF(T2.LE.TFIN)GO TO 26
      WRITE(6,2026)TFIN
 2026 FORMAT(5X,'ER     - T2 > TFIN= ',F10.2)
      GO TO 22
   26 N=T1/TSTEP+.001
      T1=N*TSTEP
      M=T2/TSTEP+.001
      T2=M*TSTEP
      NP=M-N
      IF(NP.GT.0)GO TO 23
      WRITE(6,2004)NP
 2004 FORMAT(5X,'ER    - T2 < T1')
      GO TO 22
   23 WRITE(6,1004)NP
 1004 FORMAT(//10X,'IL NUMERO DI PASSI DI INTEGRAZIONE DA COMPIERE ',
     $   'FRA T1 E T2 =',I4/10X,
     $   'ASSEGNA, SE VUOI, UN NUMERO INTERO CHE LO MOLTIPLICHI')
C
C      READ(5,1400)NCHAR,KN
C 1400 FORMAT(Q,I5)
C      IF(NCHAR.EQ.0)KN=1
C
      READ (5,1500) LEGCAR
      IF (LEGCAR .EQ. ' ') THEN
         KN = 1
      ELSE
         READ (LEGCAR, '(I5)') KN
      ENDIF
C
      CU=(UMAX-CU0/UU0)/(T2-T1)
C
C     MEMORIZZAZIONE DATI RAMPA
C
      NPER=NPER+1
      IF(NPER.GT.MXPERT)GO TO 99
      KPOS=KP+5
      IF(KPOS.GT.MXDPER)GO TO 99
      IVPER(NPER)=IPV
      ITPER(NPER)=1
      IPPER(NPER)=IPPER(NPER)+1
      DATPER(KP+1)=T1
      DATPER(KP+2)=T2
      DATPER(KP+3)=CU
      DATPER(KP+4)=UU0
      DATPER(KP+5)=KN
      KP=KP+5
      IPPER(NPER+1)=KP
      GO TO 1
C
C     PERTURBAZIONE CON LEGGE TABULATA
C
   50 WRITE(6,1008)
 1008 FORMAT(//10X,'ASSEGNA LE COORDINATE DELLA FUNZIONE'/
     $         10X,'Ti , U(Ti)=Ur(Ti)/U(0) '/)
      I=0
   65 I=I+1
      IF(I.GT.100)GO TO 70
   63 WRITE(6,1009)I
 1009 FORMAT(5X,'T',I3)
      READ (5,1500) LEGCAR
      IF (LEGCAR .EQ. ' ') THEN
         GO TO 70
      ELSE
         READ (LEGCAR, '(F10.0)') T(I)
      ENDIF
C
      IF(T(I).LE.TFIN)GO TO 64
      WRITE(6,2027)TFIN
 2027 FORMAT(5X,'TEMPO > TFIN= ',F10.2)
      GO TO 63
   64 WRITE(6,1309)I
 1309 FORMAT(5X,'U(T',I3,')')
      READ(5,1402)U(I)
 1402 FORMAT(F10.0)
   66 IF(I.EQ.1)GO TO 65
      DT=T(I)-T(I-1)
      IF(DT.GT.0.)GO TO 65
      WRITE(6,1010)
 1010 FORMAT(/10X,'ER - LA VARIABILE TEMPO NON E` CRESCENTE ' /)
      GO TO 63
C
   70 KPUN=I
      U(KPUN)=U(KPUN-1)
      T(KPUN)=TFIN+1.
C
C     MEMORIZZAZIONE DATI LEGGE TABULATA
C
      NPER=NPER+1
      IF(NPER.GT.MXPERT)GO TO 99
      KPOS=KP+2*KPUN+10
      IF(KPOS.GT.MXDPER)GO TO 99
      IVPER(NPER)=IPV
      IPPER(NPER)=IPPER(NPER)+1
      ITPER(NPER)=2
      DATPER(KP+1)=UU0
      DO 80 I=1,KPUN
      I1=2*I-1
      I2=I1+1
      DATPER(KP+1+I1)=T(I)
      DATPER(KP+1+I2)=U(I)
   80 CONTINUE
      KP=KP+1+2*KPUN
      IPPER(NPER+1)=KP
      GO TO 1
C
C      LETTURA E MEMORIZZAZIONE DATI GRADINO
C
   90 WRITE(6,1018)
 1018 FORMAT(10X,'ASSEGNA - T(GRAD.),U(T)=Ur(T)/U(0)')
      READ(5,*)TGRAD,UMAX
      IF(TGRAD.LE.TFIN)GO TO 126
      WRITE(6,2028)TFIN
 2028 FORMAT(5X,'ER   - T(GRAD.) > TFIN= ',F10.2)
      GO TO 90
  126 N=TGRAD/TSTEP+.001
      TGRAD=TSTEP*N
      NPER=NPER+1
      IF(NPER.GT.MXPERT)GO TO 99
      KPOS=KP+3
      IF(KPOS.GT.MXDPER)GO TO 99
      IVPER(NPER)=IPV
      ITPER(NPER)=3
      IPPER(NPER)=IPPER(NPER)+1
      DATPER(KP+1)=TGRAD
      DATPER(KP+2)=UU0
      DATPER(KP+3)=UMAX
      KP=KP+3
      IPPER(NPER+1)=KP
      GO TO 1
   99 WRITE(6,5000)MXPERT
 5000 FORMAT(///10X,'***SUPERATO IL N. MASSIMO DI PERTURBAZIONI',
     $          I3,/10X,'L ULTIMA VIENE TRASCURATA'//)
      NPER=NPER-1
  100 IPPER(NPER+1)=IPPER(NPER+1)+1
C
C     STAMPE OPZIONALI
C
      CALL SSWTCH(2,LL)
      IF(LL.NE.1)GO TO 120
      IF(NPER.EQ.0)GO TO 120
      WRITE(6,1011)
 1011 FORMAT(///10X,'STAMPE OPZIONALI SSWTCH 2 '/10X,
     $   'DATI DI PERTURBAZIONE '/)
      DO 110 I=1,NPER
      IPV=IVPER(I)
      IT=ITPER(I)
      I1=IPPER(I)
      I2=IPPER(I+1)-1
      GO TO (101,105,107),IT
  101 WRITE(6,3030)VARI(IPV),(DATPER(K),K=I1,I2-1)
 3030 FORMAT(//1X,'INGRESSO ',A8,2X,'RAMPA',2X,'T1=',F8.2,' T2=',F8.2,
     $   ' K=',F8.3,' U(0)=',F8.4//)
      GO TO 110
C
  105 WRITE(6,3040)VARI(IPV),(DATPER(K),K=I1,I2)
 3040 FORMAT(//1X,'INGRESSO ',A8,2X,'LEGGE TABULATA  U(0)=',F8.4/
     $   10X,'TEMPO     U/U(0)'/(10X,F8.3,2X,F8.4))
      GO TO 110
C
  107 WRITE(6,3050)VARI(IPV),(DATPER(K),K=I1,I2)
 3050 FORMAT(//1X,'INGRESSO ',A8,2X,'GRADINO ',2X,' T= ',
     $   F8.2,'  U(0)= ',F8.4,'  U= ',F8.4//)
  110 CONTINUE
  120 RETURN
      END
C            
