//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LgSincro.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LGSINCRO_DIALOG             102
#define IDD_MONITORDLG_DIALOG           105
#define IDD_NOMESNAP_DIALOG             107
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDI_START                       133
#define IDI_FREEZE                      134
#define IDI_STOP                        135
#define IDI_STEP                        136
#define IDI_LRUN                        147
#define IDI_LFREEZE                     148
#define IDI_LSTOP                       148
#define IDI_PERT                        149
#define IDI_SNAP                        153
#define IDI_SPEED                       155
#define IDI_GRAF                        156
#define IDI_LFRZE                       157
#define IDD_SCELTAVAR                   158
#define IDD_PERT                        159
#define IDI_READS                       162
#define IDI_PICT                        162
#define IDD_OPTGRAF                     170
#define IDI_UPDRED                      174
#define IDI_SF14                        175
#define IDI_KILL                        176
#define IDC_PLAY                        1000
#define IDC_FREEZE                      1001
#define IDC_STEP                        1002
#define IDC_STOP                        1003
#define IDC_PERT                        1004
#define IDC_LOG                         1005
#define IDC_SIMTIME                     1006
#define IDC_DELAY                       1007
#define IDC_SPEED                       1008
#define IDC_SNAP                        1009
#define IDC_GRAF                        1010
#define IDC_SF14                        1011
#define IDC_PINT                        1012
#define IDC_BMP                         1015
#define IDC_LSTOP                       1018
#define IDC_LRUN                        1019
#define IDC_MAXS                        1022
#define IDC_SSPEED                      1027
#define IDC_NVAR                        1028
#define IDC_SPH                         1035
#define IDC_LP                          1036
#define IDC_TIPOP                       1038
#define IDC_SPM                         1039
#define IDC_SPS                         1040
#define IDC_APPLY                       1042
#define IDC_DESCVAR                     1047
#define IDC_EDIT1                       1061
#define IDC_EDIT2                       1062
#define IDC_EDIT3                       1063
#define IDC_EDIT4                       1064
#define IDC_EDIT5                       1065
#define IDC_EDIT6                       1066
#define IDC_EDIT7                       1067
#define IDC_EDIT8                       1068
#define IDC_EDIT9                       1069
#define IDC_EDIT10                      1070
#define IDC_EDIT11                      1071
#define IDC_EDIT12                      1072
#define IDC_RADIO1                      1073
#define IDC_RADIO2                      1074
#define IDC_RADIO3                      1075
#define IDC_RADIO4                      1076
#define IDC_RADIO5                      1077
#define IDC_RADIO6                      1078
#define IDC_RADIO7                      1079
#define IDC_RADIO8                      1080
#define IDC_RADIO9                      1081
#define IDC_RADIO10                     1082
#define IDC_RADIO11                     1083
#define IDC_RADIO12                     1084
#define IDC_RIMBTT                      1085
#define IDC_CANCEL                      1085
#define IDC_IMPO2                       1086
#define IDC_DESC                        1087
#define IDC_IMPO1                       1089
#define IDC_NEWV                        1091
#define IDC_DELTAV                      1092
#define IDC_VFINAL                      1093
#define IDC_TIMEUP                      1094
#define IDC_GRAD                        1095
#define IDC_APPLYALL                    1096
#define IDC_ADDBTT                      1097
#define IDC_IMPO3                       1098
#define IDC_STATUS                      1101
#define IDC_EDIT13                      1102
#define IDC_EDIT14                      1103
#define IDC_EDIT15                      1104
#define IDC_EDIT16                      1105
#define IDC_EDIT17                      1106
#define IDC_EDIT18                      1107
#define IDC_EDIT19                      1108
#define IDC_EDIT20                      1109
#define IDC_EDIT21                      1110
#define IDC_EDIT22                      1111
#define IDC_EDIT23                      1112
#define IDC_EDIT24                      1113
#define IDC_CORRBTT                     1114
#define IDC_COMBO2                      1116
#define IDC_LIST2                       1122
#define IDC_BUTTON1                     1123
#define IDC_COMBO1                      1125
#define IDC_LIST1                       1126
#define IDC_ERASE                       1127
#define IDC_LOAD                        1128
#define IDC_SAVE                        1129
#define IDC_ADD                         1130
#define IDC_FIND                        1131
#define IDC_STATICO1                    1132
#define IDC_STATICO2                    1133
#define IDC_GRAFREFR                    1134
#define IDC_GRAFMULT                    1135
#define IDC_KILLGRAF                    1136
#define ID_SPEED                        32772
#define ID_CONTROLS_START               32773
#define ID_CONTROLS_FREEZE              32774
#define ID_CONTROLS_STEP                32775
#define ID_CONTROLS_STOP                32776
#define ID_FILE_INITFROMSNAPSHOT        32780
#define ID_FILE_INITFROMBACKTRACK       32781
#define ID_FUNCTIONS_SNAPSHOT           32783
#define ID_OPTIONS_SPEED_MAX            32786
#define ID_OPTIONS_TIME_HHMMSS          32788
#define ID_OPTIONS_TIME_ONLYSEC         32789
#define ID_CONTROLS_RUN                 32790
#define ID_FUNCTIONS_RECORDING_BACKUP   32792
#define ID_FILE_EXIT                    32793
#define ID_OPTGRAF                      32794
#define ID_INFOABOUT                    32795
#define ID_GRAPHICS_MOD                 32796
#define ID_FUNCTIONS_PERTURBATION       32800
#define ID_FUNCTIONS_GRAPHICS           32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
