/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/

#define BLANK       0x20     /* carattere <   > */
#define CAR_COMM    0x3b     /* carattere < ; > segna commenti */
#define CR          0x0a     /* carattere carriage return */
#define VIRGOLETTE  0x22     /* carattere < " > */
#define VIRGOLA     0x2c     /* carattere < , > */
#define TAB         0x09     /* carattere di tabulazione  */
#define PIU         0x2b     /* carattere < + > */
#define DUE_PUNTI   0x3a     /* carattere < : > */
#define PUNTO       0x2e     /* carattere < . > */
#define APQUADRA    0x5b     /* carattere < [ > */
#define CHQUADRA    0x5d     /* carattere < ] > */
#define APTONDA     0x28     /* carattere < ( > */
#define CHTONDA     0x29     /* carattere < ) > */
#define UNDSCORE    0x5f     /* carattere < _ > */
#define SLASH       0x2f     /* carattere < / > */
#define BAKSLASH    0x5c     /* carattere < \ > */
#define APICE       0x27     /* carattere < ' > */
#define ASTERISCO   0x2a     /* carattere < * > */
#define UGUALE      0x3d     /* carattere < = > */
#define PUNTO_INT   0x3f     /* carattere < ? > */
