#!/bin/ksh
#
grep -v C/ $KSIM/log/connex2.out | \
grep -v MANUAL | \
grep -v RHA | \
grep -v EJ | \
grep -v RHE | \
grep -v MBP5 | \
grep -v MBP8 | \
grep -v DUM | \
grep -v NS | \
grep -v RSD | \
grep -v RSF | \
grep -v LAB90 | \
grep -v PGB | \
grep -v RSN | \
grep -v RSE | \
grep -v RYB | \
grep -v PCC | \
grep -v RPJ | \
grep -v QJE | \
grep -v QJA | \
grep -v RAA | \
grep -v TAG | \
grep -v TEY | \
grep -v TNR | \
grep -v TEC | \
grep -v RKC | \
grep -v TEP | \
grep -v PAC | \
grep -v EBC | \
grep -v RKL | \
grep -v RSC | \
grep -v RPG | \
grep -v REE | \
grep -v TEK | \
grep -v RSC | \
grep -v PGC | \
grep -v PAL | \
grep -v MBU00 | \
grep -v RMM | \
grep -v RKA | \
grep -v RMS | \
grep -v EBL | \
grep -v CJG | \
grep -v LAB85 | \
grep -v TOL | \
grep -v TOL | \
grep -v LAB30 | \
grep -v SPRING | \
grep -v MAV00EY | \
grep -v MAY01EC200 | \
grep -v MBP12 | \
grep -v MAV | \
grep -v LOCAL | \
grep -v RCG | \
grep -v _ZV | \
grep -v XRXX00DA201 | \
grep -v 0MBY10DP070G | \
grep -v 0MBL10CT00 | \
grep -v 0MBL00C | \
grep -v HNE | \
grep -v XMBM11CP052 | \
grep -v TEC > $KLOG/ciclo.conn
