C******************************************************************************
C modulo lego1.f
C tipo 
C release 2.1
C data 7/10/95
C reserver @(#)lego1.f	2.1
C******************************************************************************
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                      C
C           LEGO unificato per singola / doppia precisione             C
C                 e per diverse piattaforme operative                  C
C                                                                      C
C   Attivata versione singola precisione per sistema operativo Unix    C
C                                                                      C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE  LEGO1(MODEL,FIL01,ISL,IPUNB,NOSL,LIMODU,
     $                  ICON,IPUNIN,NLF01,ITIMOD,IERTOP)
C
C               PROGRAMMA   L E G O 1
C
C      INCLUDE 'LG1_PARAMETER.F'
C**   Descrizione delle parameter di LG1
C**
C**   N000= MOLTIPLICATORE
C**
C**   N001= N. MODULI
C**   N002= N. BLOCCHI
C**   N003= N.STATI+ALG. = ORDINE MASSIMO SISTEMA ALGEBRICO
C**   N004= N. INGRESSI
C**   N005= N. VARIABILI
C**   N006= N. VAR. DI 1 BLOCCO (di processo)
C**   NT006= N. VAR. DI 1 BLOCCO (di regolazione)
C**   N007= N. DI DATI
C**   N008= N. DI EQUAZIONI DI UN BLOCCO
C**   NR00= N. DI TERMINI #0 PER OGNI EQUAZIONE
C**   NP00= N. DI PERTURBAZIONI
C
      PARAMETER (N000=70,
     $           N001=N000*10, N002=N000*25, N003=N000*50,
     $           N004=N000*25, N005=N000*100, N006=100, NT006=N003+N004,
     $           N007=N000*500, N008=40, NR00=12, NP00=10)
C
C**   M001= N. TOTALE INGRESSI    =N005-N003
C**   M002= N. INGRESSI = USCITE  =M001-N004
C
      PARAMETER (M001=N005-N003, M002=M001-N004, M003=N002+1,
     $           M004=N003+1, M005=N004+1)
C
      DIMENSION NOSL(N001),ISL(N002),NOMBLC(N002,2),NOMSUB(N002),
     $          NSTA(N002),NUSC(N002),NIGR(N002),
     $          IPV(M003),ICEI(M001),ICESU(N003)
      CHARACTER*8 VAR(NT006),VARI(N004),VARS(N005),VARBL(NT006,3),
     $            VAIN(M001),VAINU(M002),VASU(N003),VAVA
C
      CHARACTER*(*) FIL01(*),LIMODU(*)
      CHARACTER*70 LISLTM(N001)
C
      DIMENSION NOSLN(N002),ISLN(N002),IPUNB(*)
C
      CHARACTER*2 FF
      CHARACTER*8 MODEL,CPS
C
      NX1=N001
      NX2=N002
      NX3=N003
      NX4=N004
      NX5=N005
      NX6=NT006
      MX1=M001
      MX2=M002
C
C
      IERTOP=0
      WRITE(6,1000)MODEL
 1000 FORMAT('1'//10X,'CONTROLLI SUI DATI TOPOLOGICI DEL',
     $       ' MODELLO ',A8)
C
C
      IFERR=0
      KSU=0
      KERR=0
      KIN=0
      IBL=0
      NEQAL=0
      IPV(1)=0
C
C______CARICAMENTO DEI DATI TOPOLOGICI CONTENUTI NELL'AREA FIL01
C      NEI VETTORI DATI 'OLD-LEGO'
C
      DO 500 I=1,ICON
C
      KI=ISL(I)
C
      K1=IPUNB(I)
      IF(I.LT.ICON)THEN
      K2=IPUNB(I+1)-3
      ELSE
      K2=IPUNIN-2
      ENDIF
C
      READ(FIL01(K1),'(2A4)')IBLOC1,IBLOC2
C
      NSTATI=0
      NUSCIT=0
      NINGRE=0
      K=0
C
      DO 700 J=K1+1,K2
      K=K+1
      READ(FIL01(J),'(A8)')VAR(K)
C
      FF=FIL01(J)(13:14)
      IF(FF.EQ.'US'.OR.FF.EQ.'UA'.OR.FF.EQ.'IN')GO TO 344
C
      WRITE(6,1065)VAR(K),IBLOC1,IBLOC2
 1065 FORMAT(//10X,'ER- LA VARIABILE ',A8,' DEL BLOCCO ',2A4,
     $   /10X,'NON E` DEFINITA STATO (US), USCITA ALG. (UA)',
     $   ' O INGRESSO (IN)'/10X,'E CIO` NON E` AMMESSO.')
      K=K-1
      IFERR=1
C
  344 IF(FIL01(J)(13:14).EQ.'US')NSTATI=NSTATI+1
      IF(FIL01(J)(13:14).EQ.'UA')NUSCIT=NUSCIT+1
      IF(FIL01(J)(13:14).EQ.'IN')NINGRE=NINGRE+1
C
  700 CONTINUE
C
C     CONTROLLI DI VALIDITA` SUI NOMI ASSEGNATI ALLE VARIABILI DI UN
C     BLOCCO RISPETTO A QUELLE GIA' DEFINITE PER I BLOCCHI PRECEDENTI
C
      NVAR=NSTATI+NUSCIT+NINGRE
      MODO=1
C
C     1)PER IL BLOCCO DATO GLI INGRESSI,GLI STATI E LE USCITE
C       DEVONO ESSERE FRA LORO DISTINTI
C
      CALL SERVA1(MODO,VAR,NX6,1,NVAR,CPS,NPS,IER)
      IF(IER.EQ.0)GO TO 300
      IER=IER+1
      WRITE(6,1015)IBLOC1,IBLOC2,IER
 1015 FORMAT(//10X,'ER- NEL BLOCCO ',2A4,
     $  /10X,'CI SONO ',I2,' NOMI DI VARIABILI UGUALI'
     $  /10X,'E CIO` NON E` AMMESSO.')
      GO TO 303
C
  300 IF(IBL.EQ.0) GO TO 305
C
      NSU=NSTATI+NUSCIT
C
C     2)GLI STATI E LE USCITE DEL BLOCCO DATO DEVONO ESSERE DISTINTI
C       DA QUELLI DEI BLOCCHI GIA' ASSEGNATI
C
      DO 800 L=1,NSU
      VAVA=VAR(L)
           DO 799 M=1,KSU
           IF(VAVA.EQ.VASU(M)) GO TO 334
  799      CONTINUE
           GO TO 331
C
  334   WRITE(6,1020)VAVA,IBLOC1,IBLOC2
 1020   FORMAT(/10X,'LA VARIABILE DI USCITA ',A8,' DEL BLOCCO ',
     $         2A4/10X,'E` GIA` STATA DEFINITA USCITA DI ALTRI BLOCCHI')
        IER=1
  331   CONTINUE
  800 CONTINUE
C
      IF(IER.EQ.0)GO TO 305
  303 CONTINUE
      IFERR=1
      GO TO 500
C
C     SEPARAZIONE FRA STATI,USCITE DAGLI INGRESSI E MEMORIZZAZIONE
C
  305 NSU=NSTATI+NUSCIT
      DO 310 K=1,NSU
      KSU=KSU+1
      IF(KSU.LE.NX3)GO TO 308
      WRITE(6,3821)NX3
 3821 FORMAT(//10X,'SUPERATO IL NUMERO MASSIMO ',I6)
      WRITE(6,3823)
 3823 FORMAT(10X,'DI VARIABILI (STATI+ ALG.) DEL SISTEMA')
      KERR=1
      GO TO 501
  308 CONTINUE
      VASU(KSU)=VAR(K)
  310 CONTINUE
      NSU1=NSU+1
      DO 320 K=NSU1,NVAR
      KIN=KIN+1
      IF(KIN.LE.MX1)GO TO 318
      WRITE(6,3821)MX1
      WRITE(6,3824)
 3824 FORMAT(10X,'PARI ALLA SOMMA DEL NUMERO DI INGRESSI DEI BLOCCHI')
      KERR=1
      GO TO 501
  318 CONTINUE
      VAIN(KIN)=VAR(K)
  320 CONTINUE
C
C     MEMORIZZAZIONE VARIABILI E TOPOLOGIA
C
      IBL=IBL+1
      NOMBLC(IBL,1)=IBLOC1
      NOMBLC(IBL,2)=IBLOC2
      NOMSUB(IBL)=NOSL(KI)
      NSTA(IBL)=NSTATI
      I0=IPV(IBL)
      IPV(IBL+1)=I0+NVAR
      NUSC(IBL)=NUSCIT
      NIGR(IBL)=NINGRE
      DO 100 KK=1,NVAR
      II=I0+KK
      IF(II.LE.NX5)GO TO 99
      WRITE(6,3821)NX5
      WRITE(6,3825)
 3825 FORMAT(10X,'PARI ALLA SOMMA DEL NUMERO DI VARIABILI DEI BLOCCHI')
      KERR=1
      GO TO 501
   99 CONTINUE
      VARS(II)=VAR(KK)
  100 CONTINUE
      IPV(IBL)=I0+1
      NEQAL=NEQAL+NUSCIT
  500 CONTINUE
C
C______________ FINE DEL CARICAMENTO
C
  501 NBL=IBL
      IPV(IBL+1)=IPV(IBL+1)+1
C
C______ERRORI NEI DATI TOPOLOGICI
C
      IF(IFERR.EQ.1.OR.KERR.EQ.1)GO TO 171
C
C_____ CARICAMENTO NEL VETTORE VARI(I)
C      DEGLI INGRESSI DEL SISTEMA CONTENUTI IN FIL01()
C
      NU=0
      DO 900 I=IPUNIN+1,NLF01
      IF(FIL01(I)(1:4).EQ.'****')GO TO 135
      NU=NU+1
      IF(NU.LE.NX4)GO TO 131
      WRITE(6,3821)NX4
      WRITE(6,3826)
 3826 FORMAT(10X,'DI VARIABILI DI INGRESSO DEL SISTEMA')
      GO TO 171
  131 READ(FIL01(I),'(A8)')VARI(NU)
  900 CONTINUE
C
C     CONTROLLO SULLA TOPOLOGIA
C
C     1) GLI INGRESSI ASSEGNATI DEVONO ESSERE COMPRESI
C        FRA GLI INGRESSI DEI BLOCCHI
C
C     2) GLI INGRESSI DEI BLOCCHI, DIVERSI DA QUELLI ASSEGNATI,
C        DEVONO ESSERE COMPRESI FRA GLI STATI E LE USCITE
C
C     3) GLI INGRESSI ASSEGNATI NON DEVONO ESSERE COMPRESI
C        FRA GLI STATI E LE USCITE
C
  135 MODO=1
C
C_____GLI INGRESSI DEVONO ESSERE FRA LORO DISTINTI
C
      CALL SERVA1(MODO,VARI,NX4,1,NU,CPS,IPV,IER)
      IF(IER.EQ.0)GO TO 140
      IER=IER+1
      WRITE(6,1023)IER
 1023 FORMAT(/10X,'ER- FRA GLI INGRESSI DEL SISTEMA, '/
     $        10X,'CHE DEVONO ESSERE DISTINTI,'/
     $        10X,'CE NE SONO ',I2,' UGUALI'/)
      GO TO 171
C
C      CONTROLLO 1
C
  140 MODO=2
      DO 145 K=1,KIN
      ICEI(K)=0
  145 CONTINUE
      WRITE(6,1024)
 1024 FORMAT(///10X,'CONTROLLO CHE GLI INGRESSI DEL SISTEMA '/
     $          10X,'SIANO COMPRESI FRA GLI INGRESSI DEI BLOCCHI '/)
      CALL SERVA2(MODO,VARI,NX4,1,NU,VAIN,MX1,1,KIN,ICEI,IER)
C
      IF(IER.NE.0)GO TO 171
C
C      CONTROLLO 2
C
  150 NSIO=0
      DO 160 K=1,KIN
      IF(ICEI(K).EQ.1)GO TO 160
      NSIO=NSIO+1
      IF(NSIO.LE.MX2)GO TO 158
      WRITE(6,3821)MX2
      WRITE(6,3827)
 3827 FORMAT(10X,'PARI AL NUMERO DI VARIABILI DI INGRESSO',
     $      ' - USCITA DI ALTRI BLOCCHI')
      GO TO 171
  158 CONTINUE
      VAINU(NSIO)=VAIN(K)
  160 CONTINUE
C
      IF(NSIO.EQ.0)GO TO 167
      DO 165 K=1,KSU
      ICESU(K)=0
  165 CONTINUE
      MODO=2
      WRITE(6,1026)
 1026 FORMAT(/10X,'CONTROLLO CHE GLI INGRESSI DEI BLOCCHI, '/
     $        10X,'CHE NON SONO INGRESSI DEL SISTEMA, '/
     $        10X,'SIANO COMPRESI FRA GLI STATI E LE USCITE'/)
      CALL SERVA2(MODO,VAINU,MX2,1,NSIO,VASU,NX3,1,KSU,ICESU,IER)
C
  167 IF(IER.NE.0)GO TO 171
C
C      CONTROLLO 3
C
      WRITE(6,2222)
 2222 FORMAT(/10X,'CONTROLLO CHE GLI INGRESSI DEL SISTEMA NON '/
     $        10X,'COMPAIANO FRA GLI STATI E LE USCITE '/)
      MODO=1
      CALL SERVA2(MODO,VARI,NX4,1,NU,VASU,NX3,1,KSU,ICESU,IER)
      IF(IER.EQ.0) GOTO 170
C
C  171 WRITE(6,1029)
C 1029 FORMAT(/10X,'ERRORE NELLA TOPOLOGIA '
C     $   ///10X,'SUL FILE LG1.OUT TROVI I DIAGNOSTICI'//)
  171  IERTOP=1
C
C     STAMPA TOPOLOGICA
C
  170 CALL STATO1(NBL,NOMBLC,NOMSUB,NSTA,NUSC,NIGR,IPV,VARS,
     $     MODEL,NX2,NX5,NX6,VARBL)
C
  211 CONTINUE
      IF(IERTOP.EQ.0)GO TO 220
C      WRITE(6,1051)
C 1051 FORMAT(//10X,'IL FILE DATI GEOMETRICI NON VIENE PRODOTTO')
C      WRITE(6,1052)
C 1052 FORMAT(//10X,'DEVI CORREGGERE I DATI TOPOLOGICI ')
      RETURN
C
  220 CONTINUE
C
C      WRITE(6,1068)MODEL
C 1068 FORMAT(//10X,'LA TOPOLOGIA DEL MODELLO ',A8,
C     $       /10X,'RISULTA FORMALMENTE CORRETTA ')
C
      NBL1=NBL+1
      NVART=IPV(NBL+1)-1
C
C
C__________ CHIAMO LA SUBROUTINE CRLTM
C           CHE CREA LE SUBROUTINES MODI2,MODC1,MODD1
C           PER IL COLLEGAMENTO LG3/LG5 - MODULI
C           modifica NST, NOSL, ISL
C           in       NSTN,NOSLN,ISLN
C           che sono utilizzati da LG3 e LG5
C
      CALL CRLTM(NST,NOSL,LIMODU,ISL,NBL,NSTN,NOSLN,LISLTM,ISLN,ITIMOD)
C
      REWIND 2
      WRITE(2)NSTN,NBL,NEQAL, NU,NVART,NBL1
      WRITE(2)(NOSLN(I),I=1,NSTN)
      WRITE(2)MODEL
      WRITE(2)(NOMSUB(I),(NOMBLC(I,J),J=1,2),NSTA(I),NUSC(I),
     $         NIGR(I),ISLN(I),I=1,NBL),(IPV(I),I=1,NBL1)
      WRITE(2)(VARS(I),I=1,NVART)
      WRITE(2)(VARI(I),I=1,NU)
C
      WRITE(2)IPUNIN,NLF01,(IPUNB(I),I=1,NBL1),
     $        (FIL01(I),I=1,NLF01 )
C
      RETURN
      END
C            
C Procedura contenete la variabile per l'identificazione della versione
C        
      SUBROUTINE SCCS_lego1
      CHARACTER*80 SccsID
      DATA SccsId/'@(#)lego1.f	2.1\t7/10/95'/
      END
