C******************************************************************************
C modulo lgdyns.f
C tipo 
C release 2.2
C data 11/7/95
C reserver @(#)lgdyns.f	2.2
C******************************************************************************
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                      C
C           LEGO unificato per singola / doppia precisione             C
C                 e per diverse piattaforme operative                  C
C                                                                      C
C   Attivata versione singola precisione per sistema operativo Unix    C
C                                                                      C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE LGDYNS(RESTAR)
C
C     DEL PROGRAMMA  LG5SIM
C
C      INCLUDE  'LG5_PARAMETER.F'
C**   Descrizione delle parameter di LG5
C**
C**   N000= MOLTIPLICATORE
C**
C**   N001= N. MODULI
C**   N002= N. BLOCCHI
C**   N003= N. STATI+ALG. = ORDINE MASSIMO SISTEMA ALGEBRICO
C**   N004= N. INGRESSI
C**   N005= N. VARIABILI
C**   N006= N. VAR. DI 1 BLOCCO
C**   N007= N. DI DATI
C**   N008= N. DI EQUAZIONI DI UN BLOCCO
C**   NR00= N. DI TERMINI #0 PER OGNI EQUAZIONE
C**   NP00= N. DI PERTURBAZIONI
C
      PARAMETER (N000=160, N001=N000*10, N002=N000*25, N003=N000*50,
     $           N004=N000*25, N005=N000*100, N006=100,
     $           N007=N000*500, N008=40, NR00=12, NP00=10)
C
      PARAMETER (M003 = N002+1, M004 = N003+1, M005 = N004+1,
     $           M001 = N005-N003, M002 = M001-N004)
C
C**      M006 = N. TERMINI # 0 DELLO JACOBIANO
C**      M007 = N. TERMINI # 0 DELLO JACOBIANO FATTORIZZATO
C**      M010 = N.VARIABILI IN OUTPUT
C
      PARAMETER (M006 = N003*NR00, M007 = 2*M006, M008 = 5*N003,
     $           M009 = 8*N003, M010 = N004+N003, MP01 = NP00+1,
     $           MP02 = NP00*200)
C
C**************DATI GENERALI
C
      DIMENSION NOSL(N001),NOSUB(N002),NOBLC(N002,2),NUSTA(N002),
     $          NUSCI(N002),NINGR(N002),ISLB(N002),IP(M003),IPVRS(N005),
     $          IPS(M004),IPVRT(N005),IPI(M005),IPVRI(M001),
     $          XY(N003),UU(N004),XYU(N005),DATI(N007),IPDATI(M003),
     $          CNXYU(N005),IPLOT(N003),ISTMP(N003),TOLL(N003),
     $          IVPER(NP00),ITPER(NP00),IPPER(MP01),DATPER(MP02)
      COMMON/C0LG5A/XY,UU,XYU,DATI,CNXYU,TOLL,DATPER,NOSL,NOSUB,NOBLC,
     $              NUSTA,NUSCI,NINGR,ISLB,IP,IPVRS,IPS,IPVRT,IPI,
     $              IPVRI,IPDATI,IPLOT,ISTMP,IVPER,ITPER,IPPER
C
C*****DATI UTILIZZATI PER COMUNICARE AL LEGO RUN-TIME LE DIM DEL LEGO
C
      INTEGER  KN000, KN001, KN002, KN003, KN004, KN005, KN007,
     $         KM001, KM002, KM003, KM004, KM005
      COMMON/PARSKED/KN000, KN001, KN002, KN003, KN004, KN005, KN007,
     $               KM001, KM002, KM003, KM004, KM005
C
C*********MEMORIA PER LA MATRICE JACOBIANA
C
      DIMENSION IPCJ(M004),ICJ(M006),ICBJ(M006),FJ(M007),ICN(M007),
     $          IRN(M007),IKEEP(M008),IW(M009),W(N003),RHS(N003),
     $          AJAC(N008,N006),RNI(N003),RIGA(N003)
      COMMON/C0LG5B/FJ,W,RHS,AJAC,RNI,RIGA,
     $              IPCJ,ICJ,ICBJ,ICN,IRN,IKEEP,IW
C
C*********MEMORIA PER RIDEFINIZIONE DELLE REALI DIMENSIONI DEL SISTEMA
C
      DIMENSION NQMODU(N002),IPVRSV(N005),
     $          IPVVSS(N003),IPSSVV(N003),RNV(N003),XYV(N003)
      COMMON/C0LG5C/RNV,XYV,NQMODU,IPVRSV,IPVVSS,IPSSVV
C
C*********VARIABILI DI TIPO CARATTERE
C
      CHARACTER*8 VAR(N005),SIVAR(N003),VARI(N004),VARSYS(N003)
      COMMON/C0LG5D/VAR,SIVAR,VARI,VARSYS
C
C*********MEMORIA PER LA SOLUZIONE DEL SISTEMA
C
      DIMENSION TN(N003),PX(N003)
      DIMENSION RN(N003),RNO(N003),XYO(N003),CNXY(N003),CNUU(N004),
     $          ICONV(1),IVECT(M006),JVECT(M006)
C
      EQUIVALENCE (IVECT(1),IRN(1)),(JVECT(1),IRN(M006+1)),
     $            (RIGA(1),ICONV(1))
C
      DIMENSION ITITOL(20)
      COMMON/NORM/P0,H0,T0,Q0,R0,AL0,V0,DP0
      COMMON/DIMAJA/NRXJC,NCXJC
      COMMON/PARINT/ITITOL,TFIN,TSTEP,FATOLL,INTERR,TINTER
      COMMON/INTEGR/TSTOP,TEMPO,DTINT,NPAS,CDT,ALFADT
      COMMON/INPAR1/NBL,NEQAL,NEQSIS,NU,NST,NVART,NPVRT,NVRI,NDATI
      COMMON/INPARV/NQALV,NQSISV
      COMMON/PARPAR/NPER,NVPLT,NVSTP,NSTPLT,NSTSTP,KPLT,KSTP,ITERT
C
      COMMON/FIXPAS/PASFIX
      LOGICAL PASFIX
C
      LOGICAL RESTAR
      CHARACTER*8 SIGLA
C********************** TAVOLE ******************************
C       ILEGO = INDICATORE DEL PROGRAMMA CHIAMANTE LE TAVOLE
C             =1 LEGO E` IL PROGRAMMA CHIAMANTE
C             =0 NON E` IL LEGO IL PROGRAMMA CHIAMANTE
C
C       ICNTMX = CONTATORE STABILITO DAL PROGRAMMA CHIAMANTE LE TAVOLE
C                  SUPERATO IL QUALE VIENE DECRETATO LO STOP .
C
      COMMON/LGTV01/LGTEMP,ILEGO,ICOUNT,ICNTMX
      COMMON/LGTV02/LGMODU,LGBLOC
      CHARACTER*8 LGMODU,LGBLOC
      REAL LGTEMP
      ILEGO  =1

C
C*****SETTAGGIO DEI DATI DA PASSARE ALLA PARTE RUN-TIME
C
      KN000 = N000
      KN001 = N001
      KN002 = N002
      KN003 = N003
      KN004 = N004
      KN005 = N005
      KN007 = N007
      KM001 = M001
      KM002 = M002
      KM003 = M003
      KM004 = M004
      KM005 = M005

C********************** TAVOLE ******************************
C
      NX2=N002
      NX3=N003
      NX8=N008
      MX7=M007
C
      ALFADT=0.63
C
C     BLOCCO DEL PASSO DI INTEGRAZIONE SE RICHIESTO DALL'UTENTE
C
      PASFIX=.TRUE.
C
      CALL BLLEG1(IPVRS,NVART,CNXYU,CNXY,CNUU)
C
C      CALCOLO DELLE DERIVATE PX(0)
C
      NEQDIF=NEQSIS-NEQAL
      CDT=1.
       DO 5 I=1,NEQDIF
      K=NEQAL+I
      TN(I)=XY(K)
    5 CONTINUE
      ICONVE=1
C
      CALL LEGRES(NBL,ISLB,NUSTA,NUSCI,IPDATI,DATI,IP,TN,CDT,XYU,
     $   RN,ICONV,SIVAR,NX3,NEQSIS,IPVRS,TOLL,ICONVE,NOBLC,NX2,RNI,
C_________ NUOVI PARAMETRI E TAVOLE
     $   IPVVSS,IPSSVV,RNV,XY,IPS,IPVRT,NOSUB)
C
      DO 10 I=1,NEQDIF
      K=NEQAL+I
      PX(I)=RN(K)
   10 CONTINUE
C
C      INIZIALIZZAZIONE
C
      ITERT=0
      JAC=0
C
C    T_PROC=1   task di processo   T_PROC=0 task di regolazione
C
      T_PROC=1
      NPAS=0
      TEMPO=0.
      LGTEMP=TEMPO
C
      CDT=0.
      CDTN=0.
      WRITE(6,*) ' METODO IMPLICITO CON ALFA = ',ALFADT
C
      IVAI=2
      JACYES=1
      IGO=1
      ICDTR=0
      KSTEP=0
C
C     LETTURA DATI ED INIZIALIZZAZIONE REGOLAZIONE
C
      IPR=1
      CALL REG000(IPR,XY,UU,PX,DATI,NEQSIS,NU,NEQDIF,NDATI,CNXY,CNUU,
     $            TSTEP,IFINE,T_PROC,JAC,ITERT)
C
      GO TO (999, 1000) IFINE
C
C      LOOP DI INTEGRAZIONE
C
  999 CONTINUE
C
C      ESECUZIONE DI UN PASSO DI INTEGRAZIONE
C
      DTINT=TSTEP
      NPAS=NPAS+1
      TEMPO= TEMPO+ DTINT
C
      LGTEMP=TEMPO
C
C      CDT = DTINT/2.
      CDT  = DTINT*ALFADT
      CDTN = DTINT*(1.-ALFADT)
C
C______ CALCOLO DEL SECONDO MEMBRO DELLE EQUAZIONI DIFFER. DISCRETIZZATE
C
      DO 30 I=1,NEQDIF
      M=NEQAL+I
C
C      TN(I)= XY(M)+ CDT*PX(I)
      TN(I)= XY(M)+ CDTN*PX(I)
C
   30 CONTINUE
C
C     RISOLUZIONE DEL SISTEMA ALGEBRICO-DIFFERENZIALE
C
      CALL LEGBL1(NEQSIS,IPS,IPVRT,XY,XYU)
      CALL LEGBL1(NU,IPI,IPVRI,UU,XYU)
C
      CALL LGSINS(IGO,NEQSIS,IPCJ,ICJ,NBL,ISLB,NUSTA,
     $ NUSCI,IPDATI,DATI,IP,TN,CDT,XYU,RN,ICONV,SIVAR,NX3,IPVRS,
     $ TOLL,RNO,XYO,JACYES,NITERJ,NJACMX,IPS,IPVRT,XY,UU,NU,IPI,IPVRI,
     $ ICBJ,FJ,RIGA,PX,NEQAL,TEMPO,AJAC,NX8,NOBLC,NX2,RNI,ICDTR,ICDTU,
     $ IGRAD,ICN,IRN,IKEEP,IW,W,RHS,IVECT,JVECT,MX7,
C___________ NUOVI PARAMETRI E TAVOLE
     $ IPVVSS,IPSSVV,IPVRSV,RNV,NQSISV,XYV,NQMODU,NQALV,NOSUB,JAC)
C
      IPR=2
      CALL REG000(IPR,XY,UU,PX,DATI,NEQSIS,NU,NEQDIF,NDATI,CNXY,CNUU,
     $            TSTEP,IFINE,T_PROC,JAC,ITERT)
C
C      TEST  FINE TRANSITORIO
C
      IGO=0
C
      GO TO (999,1000) IFINE
 1000 CONTINUE
      RETURN
      END
C            
C Procedura contenete la variabile per l'identificazione della versione
C        
      SUBROUTINE SCCS_lgdyns
      CHARACTER*80 SccsID
      DATA SccsId/'@(#)lgdyns.f	2.2\t11/7/95'/
      END
