
	SUBROUTINE LGSERSTP
	DIMENSION XYDUM(10)
	character*8 SDUM1
	character*100 SDUM2
C
C_____CHIUSURA DI TUTTI I FILES
C
      CLOSE (10)
      CLOSE (14)
C--GUAG lug 2002
      	IVAI2=3
	CALL PREP_F22(IVAI2,NN,NSEL,TEMP,LOC(XYDUM),SDUM1,SDUM2)
C--
      CLOSE (22)
      CLOSE (21)
C

      RETURN
      END
C
