#!/usr/bin/ksh
#@(#)RGB					1997-02-26

#-----------------------------------------------------------------------
hn=`hostname | sed -e 's/\..*//'`
echo $hn

if [ $hn = ucin28 ]; then
	rgb=/usr/users/giorgio/rgb.col
fi

if [ $hn = UCIN7 ]; then
	rgb=/usr/users/pride/doc/rgb.col
fi

if [ ! -r $rgb ]; then
	echo "File: $rgb unreadable"
	exit	1
fi

lc=`wc -l $rgb | awk '{ print $1 }'`

#-----------------------------------------------------------------------

fg=`expr $RANDOM$RANDOM % $lc`
fg=`expr $fg + 1`

bg=`expr $RANDOM$RANDOM % $lc`
bg=`expr $bg + 1`

grep -n ' ' $rgb | grep "^$fg:" | sed -e 's/.*://'
FG=`grep -n ' ' $rgb | grep "^$fg:" | sed -e 's/.*://' | cut -c1-24`
echo "FG: <$FG>"

grep -n ' ' $rgb | grep "^$bg:" | sed -e 's/.*://'
BG=`grep -n ' ' $rgb | grep "^$bg:" | sed -e 's/.*://' | cut -c1-24`
echo "BG: <$FG>"

w=30
h=7
x=15
y=40

xterm -geometry ${w}x${h}+${x}+${y}  -fg $FG -bg $BG -T "$FG / $BG"  -fn -*-courier-medium-r-normal--18-*-*-*-*-*-* -cr white &

x=`expr $x + 400`
xterm -geometry ${w}x${h}+${x}+${y}  -fg $BG -bg $FG -T "$BG / $FG"  -fn -*-courier-medium-r-normal--18-*-*-*-*-*-* -cr white &

x=`expr $x + 400`
xterm -geometry ${w}x${h}+${x}+${y}                                  -fn -*-courier-medium-r-normal--18-*-*-*-*-*-* -cr white &
