/**********************************************************************
*
*       C Header:               %name%
*       Subsystem:              %subsystem%
*       Description:
*       %created_by:    %
*       %date_created:  %
*
**********************************************************************/
/*
        il file di include instesta.inc contiene le
        stringhe per l'intestazione del libro giornale
        in caso di allarmi normali e di sequenza eventi

        chan int canale di output
        mess int mstal allarmi normali
                
*/

        extern char *intes_1;
        extern char *intes_2;
        extern char *intar_1;
        extern char *intel_1;
        extern char *intel_2;
        extern char *intel_3;
        extern char *point_t;
	extern char *st_alpage;

        extern char **s_tipu;
        extern char **s_tiel;

	char *s_pag="PAG.";

