rem ===============================================================
rem
rem   modulo ins_scada_val.sql
rem   tipo 
rem   release 1.1
rem   data 4/5/96
rem   reserved @(#)ins_scada_val.sql	1.1
rem
rem                        *************
rem                        INS_SCADA_VAL
rem                        *************
rem
rem This procedure inssert all default values nedeed by SCADA tables
rem
rem First Creation 28 March 1996
rem Author M.De Chirico & E.Locatelli
rem
rem =================================================================

rem
rem  ALLARSERV
rem
TRUNCATE TABLE ALLARSERV;
INSERT INTO ALLARSERV VALUES (-10,-1,0,0,40,40,60,40,40,40,1,0,0);

rem
rem  ALLARDB
rem
TRUNCATE TABLE ALLARDB;
INSERT INTO ALLARDB VALUES (1,500,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0);

rem
rem  ALLARLINE
rem
TRUNCATE TABLE ALLARLINE;
INSERT INTO ALLARLINE VALUES (0,'PRNX','0','8','1','N');

rem
rem  CPERIF
rem
TRUNCATE TABLE CPERIF;
INSERT INTO CPERIF VALUES (0,'OSF1',32767);

rem
rem  DESCRISCHEDA
rem
TRUNCATE TABLE DESCRISCHEDA;
INSERT INTO DESCRISCHEDA VALUES ('OSF1',0,'Scheda simulatore',1,1,1,1);

rem
rem  CONFIGURAZIONEDB
rem
TRUNCATE TABLE CONFIGURAZIONEDB;
INSERT INTO CONFIGURAZIONEDB VALUES 
('PUERTO','SIMU','SIMULATORE PUERTO','ENEL',32767,32767,32767,32767,32767,32767,32767,
32767,32767,32767,100,100);

rem
rem  ALLARLIV
rem
TRUNCATE TABLE ALLARLIV;
INSERT INTO ALLARLIV VALUES (1,'RO','MA','GI','________','________');
INSERT INTO ALLARLIV VALUES (2,'BI','BI','BI','DIAGNOST','DIAGNOST');
INSERT INTO ALLARLIV VALUES (3,'RO','BI','VE','________','STRINGA_');
INSERT INTO ALLARLIV VALUES (4,'RO','BI','GI','________','COM.ESEG');
INSERT INTO ALLARLIV VALUES (5,'RO','MA','GI','NO_ALTMO','ALTIS.MO');
INSERT INTO ALLARLIV VALUES (6,'RO','MA','GI','NO_BASMO','BASSI.MO');
INSERT INTO ALLARLIV VALUES (7,'RO','MA','GI','NO_ALTO_','ALTO____');
INSERT INTO ALLARLIV VALUES (8,'RO','MA','GI','NO_BASSO','BASSO___');
INSERT INTO ALLARLIV VALUES (9,'RO','BI','VE','IN_SCANS','FORZATO_');
INSERT INTO ALLARLIV VALUES (10,'MA','MA','MA','ATTENDIB','INATTEND');
INSERT INTO ALLARLIV VALUES (11,'BL','BL','BL','IN_SCANS','NO_SCANS');
INSERT INTO ALLARLIV VALUES (12,'RO','BI','VE','NO_GR.VA','GRA.VAR.');
INSERT INTO ALLARLIV VALUES (13,'RO','BI','VE','IN_SC_AL','SCALA_AL');
INSERT INTO ALLARLIV VALUES (14,'RO','BI','VE','IN_SC_BA','SCALA_BA');
INSERT INTO ALLARLIV VALUES (15,'RO','BI','VE','TRSDT.OK','TRSDT.KO');
INSERT INTO ALLARLIV VALUES (16,'RO','BI','VE','GI.FR.OK','GI.FR.KO');
INSERT INTO ALLARLIV VALUES (17,'VE','VE','VE','________','________');
INSERT INTO ALLARLIV VALUES (18,'RO','BI','VE','________','COMANDO_');
INSERT INTO ALLARLIV VALUES (19,'RO','BI','VE','________','ERR.CONF');
INSERT INTO ALLARLIV VALUES (20,'BI','MA','GI','________','________');
INSERT INTO ALLARLIV VALUES (21,'RO','BI','VE','________','VAR.ORG.');
INSERT INTO ALLARLIV VALUES (22,'RO','BI','VE','________','COM.FALL');
INSERT INTO ALLARLIV VALUES (23,'RO','BI','VE','________','PRO.FALL');
INSERT INTO ALLARLIV VALUES (24,'RO','BI','VE','________','COM.OPER');
INSERT INTO ALLARLIV VALUES (25,'RO','BI','VE','________','COM.PROG');
INSERT INTO ALLARLIV VALUES (26,'RO','BI','VE','________','LI.ALTMO');
INSERT INTO ALLARLIV VALUES (27,'RO','BI','VE','________','LI.ALTO_');
INSERT INTO ALLARLIV VALUES (28,'RO','BI','VE','________','LI.BASMO');
INSERT INTO ALLARLIV VALUES (29,'RO','BI','VE','________','LI.BASSO');
INSERT INTO ALLARLIV VALUES (30,'RO','BI','VE','SIGNAL_A','NO_SIG_A');
INSERT INTO ALLARLIV VALUES (31,'RO','BI','VE','SIGNAL_B','NO_SIG_B');
INSERT INTO ALLARLIV VALUES (32,'RO','BI','VE','SIGNAL_C','NO_SIG_C');
INSERT INTO ALLARLIV VALUES (33,'RO','BI','VE','SIGNAL_D','NO_SIG_D');
INSERT INTO ALLARLIV VALUES (34,'RO','BI','VE','SIGNAL_E','NO_SIG_E');
INSERT INTO ALLARLIV VALUES (35,'RO','BI','VE','SIGNAL_F','NO_SIG_F');
INSERT INTO ALLARLIV VALUES (36,'RO','BI','VE','SIGNAL_G','NO_SIG_G');
INSERT INTO ALLARLIV VALUES (37,'RO','BI','VE','SIGNAL_H','NO_SIG_H');
INSERT INTO ALLARLIV VALUES (38,'RO','BI','VE','SIGNAL_I','NO_SIG_I');
INSERT INTO ALLARLIV VALUES (39,'RO','BI','VE','SIGNAL_J','NO_SIG_J');
INSERT INTO ALLARLIV VALUES (40,'RO','BI','VE','SIGNAL_K','NO_SIG_K');
INSERT INTO ALLARLIV VALUES (41,'RO','BI','VE','SIGNAL_L','NO_SIG_L');
INSERT INTO ALLARLIV VALUES (42,'RO','BI','VE','SIGNAL_M','NO_SIG_M');
INSERT INTO ALLARLIV VALUES (43,'RO','BI','VE','SIGNAL_N','NO_SIG_N');
INSERT INTO ALLARLIV VALUES (44,'RO','BI','VE','SIGNAL_O','NO_SIG_O');
INSERT INTO ALLARLIV VALUES (45,'RO','BI','VE','SIGNAL_P','NO_SIG_P');
INSERT INTO ALLARLIV VALUES (46,'RO','BI','VE','SIGNAL_Q','NO_SIG_Q');
INSERT INTO ALLARLIV VALUES (47,'RO','BI','VE','SIGNAL_R','NO_SIG_R');
INSERT INTO ALLARLIV VALUES (48,'RO','BI','VE','SIGNAL_S','NO_SIG_S');
INSERT INTO ALLARLIV VALUES (49,'RO','BI','VE','SIGNAL_T','NO_SIG_T');
INSERT INTO ALLARLIV VALUES (50,'RO','BI','VE','SIGNAL_U','NO_SIG_U');
INSERT INTO ALLARLIV VALUES (51,'RO','BI','VE','SIGNAL_X','NO_SIG_X');
INSERT INTO ALLARLIV VALUES (52,'RO','BI','VE','SIGNAL_Y','NO_SIG_Y');
INSERT INTO ALLARLIV VALUES (53,'RO','BI','VE','SIGNAL_W','NO_SIG_W');
INSERT INTO ALLARLIV VALUES (54,'RO','BI','VE','SIGNAL_Z','NO_SIG_Z');

rem
rem  ALLARSTRAT
rem
TRUNCATE TABLE ALLARSTRAT;
INSERT INTO ALLARSTRAT VALUES
(1,0,-1,-1,-1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0);
INSERT INTO ALLARSTRAT VALUES
(2,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
INSERT INTO ALLARSTRAT VALUES
(3,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
INSERT INTO ALLARSTRAT VALUES
(4,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
INSERT INTO ALLARSTRAT VALUES
(5,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
INSERT INTO ALLARSTRAT VALUES
(9,0,-1,-1,-1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
INSERT INTO ALLARSTRAT VALUES
(10,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
INSERT INTO ALLARSTRAT VALUES
(11,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
INSERT INTO ALLARSTRAT VALUES
(12,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);

rem
rem  MISTABK
rem
TRUNCATE TABLE MISTABK;
INSERT INTO MISTABK VALUES (0,0);
INSERT INTO MISTABK VALUES (1,0);
INSERT INTO MISTABK VALUES (2,0);
INSERT INTO MISTABK VALUES (3,0);
INSERT INTO MISTABK VALUES (4,0);
INSERT INTO MISTABK VALUES (5,0);
INSERT INTO MISTABK VALUES (6,0);
INSERT INTO MISTABK VALUES (7,0);
INSERT INTO MISTABK VALUES (8,0);
INSERT INTO MISTABK VALUES (9,0);
INSERT INTO MISTABK VALUES (10,0);
INSERT INTO MISTABK VALUES (11,0);
INSERT INTO MISTABK VALUES (12,0);
INSERT INTO MISTABK VALUES (13,0);
INSERT INTO MISTABK VALUES (14,0);
INSERT INTO MISTABK VALUES (15,0);
INSERT INTO MISTABK VALUES (16,0);
INSERT INTO MISTABK VALUES (17,0);
INSERT INTO MISTABK VALUES (18,0);
INSERT INTO MISTABK VALUES (19,0);
INSERT INTO MISTABK VALUES (20,0);
INSERT INTO MISTABK VALUES (21,0);
INSERT INTO MISTABK VALUES (22,0);
INSERT INTO MISTABK VALUES (23,0);
INSERT INTO MISTABK VALUES (24,0);
INSERT INTO MISTABK VALUES (25,0);
INSERT INTO MISTABK VALUES (26,0);
INSERT INTO MISTABK VALUES (27,0);
INSERT INTO MISTABK VALUES (28,0);
INSERT INTO MISTABK VALUES (29,0);
INSERT INTO MISTABK VALUES (30,0);
INSERT INTO MISTABK VALUES (31,0);
INSERT INTO MISTABK VALUES (32,0);
INSERT INTO MISTABK VALUES (33,0);
INSERT INTO MISTABK VALUES (34,0);
INSERT INTO MISTABK VALUES (35,0);
INSERT INTO MISTABK VALUES (36,0);
INSERT INTO MISTABK VALUES (37,0);
INSERT INTO MISTABK VALUES (38,0);
INSERT INTO MISTABK VALUES (39,0);
INSERT INTO MISTABK VALUES (40,0);
INSERT INTO MISTABK VALUES (41,0);
INSERT INTO MISTABK VALUES (42,0);
INSERT INTO MISTABK VALUES (43,0);
INSERT INTO MISTABK VALUES (44,0);
INSERT INTO MISTABK VALUES (45,0);
INSERT INTO MISTABK VALUES (46,0);
INSERT INTO MISTABK VALUES (47,0);
INSERT INTO MISTABK VALUES (48,0);
INSERT INTO MISTABK VALUES (49,0);
INSERT INTO MISTABK VALUES (50,0);
INSERT INTO MISTABK VALUES (51,0);
INSERT INTO MISTABK VALUES (52,0);
INSERT INTO MISTABK VALUES (53,0);
INSERT INTO MISTABK VALUES (54,0);
INSERT INTO MISTABK VALUES (55,0);
INSERT INTO MISTABK VALUES (56,0);
INSERT INTO MISTABK VALUES (57,0);
INSERT INTO MISTABK VALUES (58,0);
INSERT INTO MISTABK VALUES (59,0);
INSERT INTO MISTABK VALUES (60,0);
INSERT INTO MISTABK VALUES (61,0);
INSERT INTO MISTABK VALUES (62,0);
INSERT INTO MISTABK VALUES (63,0);
INSERT INTO MISTABK VALUES (64,0);
INSERT INTO MISTABK VALUES (65,0);
INSERT INTO MISTABK VALUES (66,0);
INSERT INTO MISTABK VALUES (67,0);
INSERT INTO MISTABK VALUES (68,0);
INSERT INTO MISTABK VALUES (69,0);
INSERT INTO MISTABK VALUES (70,0);
INSERT INTO MISTABK VALUES (71,0);
INSERT INTO MISTABK VALUES (72,0);
INSERT INTO MISTABK VALUES (73,0);
INSERT INTO MISTABK VALUES (74,0);
INSERT INTO MISTABK VALUES (75,0);
INSERT INTO MISTABK VALUES (76,0);
INSERT INTO MISTABK VALUES (77,0);
INSERT INTO MISTABK VALUES (78,0);
INSERT INTO MISTABK VALUES (79,0);
INSERT INTO MISTABK VALUES (80,0);
INSERT INTO MISTABK VALUES (81,0);
INSERT INTO MISTABK VALUES (82,0);
INSERT INTO MISTABK VALUES (83,0);
INSERT INTO MISTABK VALUES (84,0);
INSERT INTO MISTABK VALUES (85,0);
INSERT INTO MISTABK VALUES (86,0);
INSERT INTO MISTABK VALUES (87,0);
INSERT INTO MISTABK VALUES (88,0);
INSERT INTO MISTABK VALUES (89,0);
INSERT INTO MISTABK VALUES (90,0);
INSERT INTO MISTABK VALUES (91,0);
INSERT INTO MISTABK VALUES (92,0);
INSERT INTO MISTABK VALUES (93,0);
INSERT INTO MISTABK VALUES (94,0);
INSERT INTO MISTABK VALUES (95,0);
INSERT INTO MISTABK VALUES (96,0);
INSERT INTO MISTABK VALUES (97,0);
INSERT INTO MISTABK VALUES (98,0);
INSERT INTO MISTABK VALUES (99,0);
INSERT INTO MISTABK VALUES (100,0);
INSERT INTO MISTABK VALUES (101,0);
INSERT INTO MISTABK VALUES (102,0);
INSERT INTO MISTABK VALUES (103,0);
INSERT INTO MISTABK VALUES (104,0);
INSERT INTO MISTABK VALUES (105,0);
INSERT INTO MISTABK VALUES (106,0);
INSERT INTO MISTABK VALUES (107,0);
INSERT INTO MISTABK VALUES (108,0);
INSERT INTO MISTABK VALUES (109,0);
INSERT INTO MISTABK VALUES (110,0);
INSERT INTO MISTABK VALUES (111,0);
INSERT INTO MISTABK VALUES (112,0);
INSERT INTO MISTABK VALUES (113,0);
INSERT INTO MISTABK VALUES (114,0);
INSERT INTO MISTABK VALUES (115,0);
INSERT INTO MISTABK VALUES (116,0);
INSERT INTO MISTABK VALUES (117,0);
INSERT INTO MISTABK VALUES (118,0);
INSERT INTO MISTABK VALUES (119,0);
INSERT INTO MISTABK VALUES (120,0);
INSERT INTO MISTABK VALUES (121,0);
INSERT INTO MISTABK VALUES (122,0);
INSERT INTO MISTABK VALUES (123,0);
INSERT INTO MISTABK VALUES (124,0);
INSERT INTO MISTABK VALUES (125,0);
INSERT INTO MISTABK VALUES (126,0);
INSERT INTO MISTABK VALUES (127,0);

rem
rem  TDIZST
rem
TRUNCATE TABLE TDIZST;
INSERT INTO TDIZST VALUES ('TRANS.',0);
INSERT INTO TDIZST VALUES ('INCONG.',1);
INSERT INTO TDIZST VALUES ('APERTA',2);
INSERT INTO TDIZST VALUES ('CHIUSA',3);
INSERT INTO TDIZST VALUES ('MARCIA',4);
INSERT INTO TDIZST VALUES ('ARRESTO',5);
INSERT INTO TDIZST VALUES ('APERTE',6);
INSERT INTO TDIZST VALUES ('CHIUSE',7);
INSERT INTO TDIZST VALUES ('SPENTE',8);
INSERT INTO TDIZST VALUES ('ACCESE',9);
INSERT INTO TDIZST VALUES ('SPENTO',10);
INSERT INTO TDIZST VALUES ('ACCESO',11);
INSERT INTO TDIZST VALUES ('ASSENTE',12);
INSERT INTO TDIZST VALUES ('PRESENTE',13);
INSERT INTO TDIZST VALUES ('IN.SERV',14);
INSERT INTO TDIZST VALUES ('F..SERV.',15);
INSERT INTO TDIZST VALUES ('A.SELEZ.',16);
INSERT INTO TDIZST VALUES ('B.SELEZ.',17);
INSERT INTO TDIZST VALUES ('SPENTI',18);
INSERT INTO TDIZST VALUES ('ACCESI',19);
INSERT INTO TDIZST VALUES ('A',20);
INSERT INTO TDIZST VALUES ('B',21);
INSERT INTO TDIZST VALUES ('X',22);
INSERT INTO TDIZST VALUES ('F',23);
INSERT INTO TDIZST VALUES ('EROGAZ.',24);
INSERT INTO TDIZST VALUES ('STOCC.',25);
INSERT INTO TDIZST VALUES ('BLOCCO',26);
INSERT INTO TDIZST VALUES ('APERTO',27);
INSERT INTO TDIZST VALUES ('CHIUSO',28);
INSERT INTO TDIZST VALUES ('',29);
INSERT INTO TDIZST VALUES ('',30);
INSERT INTO TDIZST VALUES ('',31);
INSERT INTO TDIZST VALUES ('',32);
INSERT INTO TDIZST VALUES ('',33);
INSERT INTO TDIZST VALUES ('',34);
INSERT INTO TDIZST VALUES ('',35);
INSERT INTO TDIZST VALUES ('',36);
INSERT INTO TDIZST VALUES ('',37);
INSERT INTO TDIZST VALUES ('',38);
INSERT INTO TDIZST VALUES ('',39);
INSERT INTO TDIZST VALUES ('',40);
INSERT INTO TDIZST VALUES ('',41);
INSERT INTO TDIZST VALUES ('',42);
INSERT INTO TDIZST VALUES ('',43);
INSERT INTO TDIZST VALUES ('',44);
INSERT INTO TDIZST VALUES ('',45);
INSERT INTO TDIZST VALUES ('',46);
INSERT INTO TDIZST VALUES ('',47);
INSERT INTO TDIZST VALUES ('',48);
INSERT INTO TDIZST VALUES ('',49);
INSERT INTO TDIZST VALUES ('',50);
INSERT INTO TDIZST VALUES ('',51);
INSERT INTO TDIZST VALUES ('',52);
INSERT INTO TDIZST VALUES ('',53);
INSERT INTO TDIZST VALUES ('',54);
INSERT INTO TDIZST VALUES ('',55);
INSERT INTO TDIZST VALUES ('',56);
INSERT INTO TDIZST VALUES ('',57);
INSERT INTO TDIZST VALUES ('',58);
INSERT INTO TDIZST VALUES ('',59);
INSERT INTO TDIZST VALUES ('',60);
INSERT INTO TDIZST VALUES ('',61);
INSERT INTO TDIZST VALUES ('',62);
INSERT INTO TDIZST VALUES ('',63);

rem
rem COMMIT

COMMIT;

