drop table tdpunaa;
create table LEGOSVIL.TDPUNAA
        (
 Sigla   VARCHAR2(10) CONSTRAINT pk_puntaa PRIMARY KEY,
 Descrizione                             VARCHAR2(24),
 Morsetticampo                           VARCHAR2(24),
 cavo                                    VARCHAR2(8),
 Morsettisistema                         VARCHAR2(24),
 TipoPeriferica                          VARCHAR2(4),
 IDperi                                  NUMBER(5),
 Nomescheda                              VARCHAR2(10),
 IDscheda                                NUMBER(5),
 IDpunto                                 NUMBER(5),
 Unitamisura                             VARCHAR2(10),
 Periodo                                 NUMBER(5),
 TipoSegnale                             VARCHAR2(4),
 CSbasso                                 NUMBER(10),
 CSalto                                  NUMBER(10),
 IdAttendibile                           NUMBER(5),
 CoeffGV                                 NUMBER(5),
 TipoConversione                         VARCHAR2(4),
 FSbasso                                 FLOAT(126),
 FSalto                                  FLOAT(126),
 Coeff0                                  FLOAT(126),
 Coeff1                                  FLOAT(126),
 Coeff2                                  FLOAT(126),
 Coeff3                                  FLOAT(126),
 Coeff4                                  FLOAT(126),
 GiuntoFreddo                            VARCHAR2(10),
 Coeffiltro                              FLOAT(126),
 Limite0                                 FLOAT(126),
 Zonaimpianto                            NUMBER(5),
 LalBC                                   VARCHAR2(10),
 LalBS                                   VARCHAR2(10),
 LalAC                                   VARCHAR2(10),
 LalAS                                   VARCHAR2(10),
 BandaMorta                              NUMBER(5),
 Trattamento                             NUMBER(5),
 Severita                                NUMBER(5),
 Note                                    VARCHAR2(32),
 Dainstallare                            NUMBER(5),
 SiglaSim                                VARCHAR2(16),
 Gerarchia                               VARCHAR2(18)
        );
