#
# This makefile was expanded from makefile-2 by Telelogic.
# Expanded macros and dependencies may be found at the
# end of this file
#

#
#       Makefile Header:               Makefile.mk
#       Subsystem:              56
#       Description:
#       %created_by:    lomgr %
#       %date_created:   Wed Feb 15 20:14:08 2006 %


PREFIXBIN= ../../bin

FFLAGS = $(F_FLAGS)

LIBUTIL = $(LEGO_LIB)/vapo.a

SORGENTI  = h2o_tab.for
OGGETTI   = h2o_tab.o
SHELLFILE = tables.tcl


all: $(PREFIXBIN)/h2o_tab $(PREFIXBIN)/tables.tcl


${PREFIXBIN}/h2o_tab: $(SORGENTI)
	g77 $(FFLAGS) $? $(LIBUTIL) -lm  $(F_LIB) -o $@


$(PREFIXBIN)/tables.tcl: $(SHELLFILE)
	cp $? $@



# ******* Telelogic expanded section *******

# make_macros from makefile "makefile-2"
LEGO_LIB=../../lego_big/lib


# make_macros from project "Alg_legopc-2007A1_RHE4_lomgr
#CFLAGS = -g -Wall
F_FLAGS=-fno-second-underscore -g -fno-automatic -finit-local-zero
CFLAGS = -Wall -DLinux
CC = gcc
