CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                      C
C           LEGO unificato per singola / doppia precisione             C
C                 e per diverse piattaforme operative                  C
C                                                                      C
C   Attivata versione singola precisione per sistema operativo Unix    C
C                                                                      C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      PROGRAM LG1
C
C               PROGRAMMA   L G 1
C
C      INCLUDE 'LG1_PARAMETER.F'
C**   Descrizione delle parameter di LG1
C**
C**   N000= MOLTIPLICATORE
C**
C**   N001= N. MODULI
C**   N002= N. BLOCCHI
C**   N003= N.STATI+ALG. = ORDINE MASSIMO SISTEMA ALGEBRICO
C**   N004= N. INGRESSI
C**   N005= N. VARIABILI
C**   N006= N. VAR. DI 1 BLOCCO (di processo)
C**   NT006= N. VAR. DI 1 BLOCCO (di regolazione)
C**   N007= N. DI DATI
C**   N008= N. DI EQUAZIONI DI UN BLOCCO
C**   NR00= N. DI TERMINI #0 PER OGNI EQUAZIONE
C**   NP00= N. DI PERTURBAZIONI
C
      PARAMETER (N000=70,
     $           N001=N000*10, N002=N000*25, N003=N000*50,
     $           N004=N000*25, N005=N000*100, N006=100, NT006=N003+N004,
     $           N007=N000*500, N008=40, NR00=12, NP00=10)
C
C**   M001= N. TOTALE INGRESSI    =N005-N003
C**   M002= N. INGRESSI = USCITE  =M001-N004
C
      PARAMETER (M001=N005-N003, M002=M001-N004, M003=N002+1,
     $           M004=N003+1, M005=N004+1)
C
      PARAMETER (MN005=2*N005)
      PARAMETER (MAXCAR=80)
      DIMENSION NOSL(N001)
      DIMENSION NASL(N002),ISL(N002)
      CHARACTER*(MAXCAR) LIMODU(N001)
      INTEGER      IPUNB(N002)
      CHARACTER*80 FIL01(MN005)
C
C______ FILES DI LAVORO DI LG1
C
      CHARACTER*32 LMODUL,F01DAT,F02DAT,LTMFOR,CLTMDA,LG1ERR
C
      COMMON/LG1FLS/LMODUL,F01DAT,F02DAT,LTMFOR,CLTMDA,LG1ERR
C
      CHARACTER*8 MODEL
C
      DATA IFO/7/
      DATA IF01/1/
C

      MAXMOD=N001
      MAXBLO=N002
C
C______ DEFINIZIONE DEI FILES DI LAVORO DI LG1
C
      CALL LG1FIL
C
C     APERTURA DEI FILES DI LAVORO
      OPEN(UNIT=04,FILE=LMODUL,STATUS='OLD')
      OPEN(UNIT=IF01,FILE=F01DAT,STATUS='OLD')
      OPEN(UNIT=2,FILE=F02DAT,STATUS='UNKNOWN',FORM='UNFORMATTED')
      OPEN(UNIT=35,FILE=LTMFOR,STATUS='UNKNOWN')
      OPEN(UNIT=34,FILE=CLTMDA,STATUS='UNKNOWN')
C
C  LETTURA ELENCO DEI MODULI DA FILE LMODUL.DAT
C
      CALL LISMOD(LIMODU,NOSL,NST,
     $            MAXMOD,LG1ERR,FIL01,IER)
      IF (IER.EQ.1) THEN
        WRITE (6,*) 'SI VOGLIONO USARE PIU` DI 300 MODULI'
        CALL LGABRT
      ENDIF
C
      ICON=0
C
C     LETTURA DEI NOMI DEI BLOCCHI DA FILE F01DAT
C
      CALL LETF01(IF01,ICON,ISL,NASL,NST,NOSL,MAXBLO,
     $            IPUNB,FIL01,IER,LG1ERR,MODEL,IPUNIN,
     $            NLF01)
C
      CLOSE (01)
      CLOSE (04)
      CLOSE (08)
C
      IF (IER.NE.0) THEN
        WRITE (6,*) 'ESECUZIONE INTERROTTA PER ERRORI'
        CALL LGABRT
      ENDIF
      IF (ICON.LE.0) THEN
        WRITE (6,*)
     $     'ESECUZIONE INTERROTTA - FILE TOPOLOGICO SENZA BLOCCHI'
        CALL LGABRT
      ENDIF
C
      ITIMOD=1
C
C___________ CONTROLLI SUI DATI TOPOLOGICI
C
      CALL LEGO1(MODEL,FIL01,ISL,IPUNB,NOSL,LIMODU,
     $           ICON,IPUNIN,NLF01,ITIMOD,IERTOP)
C
      CLOSE (02)
      CLOSE (34)
      CLOSE (35)
C
      IF(IERTOP.NE.0) CALL LGABRT
      CALL LGSTOP
      STOP
      END
