CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                      C
C           LEGO unificato per singola / doppia precisione             C
C                 e per diverse piattaforme operative                  C
C                                                                      C
C   Attivata versione singola precisione per sistema operativo Unix    C
C                                                                      C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      PROGRAM LG4
C
C      PROGRAMMA  L E G O 4
C
C      INCLUDE 'LG4_PARAMETER.F'
C**   Descrizione delle parameter di LG4
C**
C**   N000= MOLTIPLICATORE
C**
C**   N001= N. MODULI
C**   N002= N. BLOCCHI
C**   N003= N. STATI+ALG. = ORDINE MASSIMO SISTEMA ALGEBRICO
C**   N004= N. INGRESSI
C**   N005= N. VARIABILI
C**   N006= N. VAR. DI 1 BLOCCO
C**   N007= N. DI DATI
C**   N008= N. DI EQUAZIONI DI UN BLOCCO
C**   NR00= N. DI TERMINI #0 PER OGNI EQUAZIONE
C**   NP00= N. DI PERTURBAZIONI
C
      PARAMETER (N000=70, N001=N000*10, N002=N000*25, N003=N000*50,
     $           N004=N000*25, N005=N000*100, N006=100,
     $           N007=N000*500, N008=40, NR00=12, NP00=10)
C
C**   M001= N. TOTALE INGRESSI =N005-N003
C**   M002= N. INGRESSI = USCITE  =M001-N004
C
      PARAMETER (M001=N005-N003, M002=M001-N004, M003=N002+1,
     $           M004=N003+1, M005=N004+1, M009=N003+N004,
     $           MP01=NP00+1, MP02=NP00*30)
C
C         M006=N.TERMINI # 0 DELLO JACOBIANO DEL SISTEMA
C         M007=N.TERMINI # 0 DELLO JACOBIANO FATTORIZZATO
C
      PARAMETER (M006=N003*NR00, M007=2*M006, M008=8*N003)
C
      DIMENSION NOSL(N001),NOSUB(N002),NOBLC(N002,2),
     $          NUSTA(N002),NUSCI(N002),NINGR(N002),ISLB(N002),IP(M003),
     $          IPVRS(N005),IPS(M004),
     $          IPVRT(N005),IPI(M005),IPVRI(M001),XY(N003),UU(N004),
     $          XYU(N005),CNXYU(N005),CNUU(N004),DATI(N007),
     $          IPDATI(M003),TOLL(N003),CNXY(N003),
     $          IPLOT(M009),ISTMP(M009),
C
C    PERTURBAZIONI
C
     $          IVPER(NP00),ITPER(NP00),IPPER(MP01),DATPER(MP02)
C
      CHARACTER*8 VARI(N004),VAR(N005),SIVAR(N003)
C
      CHARACTER*100 NMSIVA(N003)
      CHARACTER*100 NMVARI(N004)
      CHARACTER*80  NMBLOC(N002)
      DIMENSION IOUSIV(N003)
      DIMENSION IOUVAR(N004)
C
      CHARACTER*100 GIASEL(N005+N002)
      CHARACTER*32  NMSAVE,FILE04
      DIMENSION ITITOL(20)
      COMMON/NORM/P0,H0,T0,Q0,R0,AL0,V0,DP0
      COMMON/PARINT/ITITOL,TFIN,TSTEP,FATOLL,INTERR,TINTER
C
      DATA ISI/'SI'/
C
C     PROGRAMMA PER LA LETTURA DATI DI SIMULAZIONE E PER ESEGUIRE
C     LE ELABORAZIONI INIZIALI DOVUTE ALLA TOPOLOGIA DEL SISTEMA
C
      NX1=N001
      NX2=N002
      NX3=N003
      NX4=N004
      NX5=N005
      NX6=N006
      NX8=N008
      MX1=M001
      MX2=M002
      MXPERT=NP00
      MXDPER=MP02
C
      WRITE(6,1000)
 1000 FORMAT(1H1//10X,'PROGRAMMA LEGO - ACQUISIZIONE DATI DI ',
     $   'SIMULAZIONE'//)
      KS=9
      CALL SSWTCH(KS,LL)
      IF(KS.EQ.9)GO TO 798
      CALL PSWTCH(5)
      CALL SSWTCH(KS,LL)
  798 CONTINUE
C
C     LETTURA DATI DA FILE 04 DI LG3
C
      FILE04 = 'proc\f04.dat'
      OPEN(04,FILE=FILE04,FORM='UNFORMATTED',STATUS='UNKNOWN')
      REWIND 04
      READ(4)NBL,NEQAL,NBL1,NVART,NEQSIS,NEQS1,NPVRT,NU,NU1,NVRI
      READ(4)ISSIS,NBTRI,NST,SIGLA,(NOSL(I),I=1,NST)
      READ(4)(NOSUB(I),NOBLC(I,1),NOBLC(I,2),NUSTA(I),NUSCI(I),
     $       NINGR(I),ISLB(I),NMBLOC(I),I=1,NBL)
      READ(4)(IP(I),I=1,NBL1),(VAR(I),IPVRS(I),I=1,NVART)
      READ(4)(IPS(I),I=1,NEQS1),(SIVAR(I),NMSIVA(I),
     $        IOUSIV(I),I=1,NEQSIS),
     $       (IPVRT(I),I=1,NPVRT)
      READ(4)(IPI(I),I=1,NU1),(VARI(I),NMVARI(I),
     $        IOUVAR(I),I=1,NU),
     $       (IPVRI(I),I=1,NVRI)
      READ(4)P0,H0,T0,Q0,R0,AL0,V0,DP0
      READ(4)(XY(I),I=1,NEQSIS),(UU(I),I=1,NU),(XYU(I),I=1,NVART)
      READ(4)NDATI,(IPDATI(I),I=1,NBL1),(DATI(I),I=1,NDATI),
     $       (CNXYU(I),I=1,NVART),(TOLL(I),I=1,NEQSIS)
      READ(4)IREGIM
      IF(IREGIM.NE.0) WRITE(6,1001)
 1001 FORMAT(//2X,'*** ATTENZIONE IL REGIME INIZIALE  N O N  E'' ',
     $   'STATO CALCOLATO ***'/)
C
C
C  costruzione normalizzazione ingressi CNUU,CNXY
C
      CALL BLLEG1(IPVRS,NVART,CNXYU,CNXY,CNUU)
C
C     LETTURA DEI PARAMETRI DI COMANDO ALLA SIMULAZIONE
C
      CALL PARSIM
C
C     LETTURA DELLE PERTURBAZIONI DEGLI INGRESSI
C
      CALL LEPERT(VARI,NX4,UU,NU,TSTEP,NPER,IVPER,ITPER,IPPER,DATPER,
     $            MXPERT,CNUU,MXDPER)
C     LETTURA DATI DI OUTPUT
C
      CALL LEOUT(NEQSIS,SIVAR,NX3,NU,VARI,NX4,NVPLT,NSTPLT,IPLOT,
     $           NVSTP,NSTSTP,ISTMP)
C
C
C     REGISTRAZIONE DEL FILE 10 - LEGO4 - LEGO5
C
  110 CONTINUE
      NSEL=1
      WRITE(4)(ITITOL(I),I=1,20),TFIN,TSTEP,FATOLL,INTERR,TINTER
      NP1=NPER+1
      NP2=IPPER(NP1)-1
      WRITE(4)NPER,NP1,NP2,(IVPER(I),ITPER(I),I=1,NPER),
     $   (IPPER(I),I=1,NP1),(DATPER(I),I=1,NP2)
      K1=1
      K2=1
      IF(NVPLT.EQ.0.OR.NVPLT.GT.999)GO TO 120
      K1=NVPLT
  120 IF(NVSTP.EQ.0.OR.NVSTP.GT.999)GO TO 130
      K2=NVSTP
  130 WRITE(4)NVPLT,NVSTP,NSTPLT,NSTSTP,K1,K2,(IPLOT(I),I=1,K1),
     $       (ISTMP(I),I=1,K2),NSEL,(GIASEL(I),I=1,NSEL)
C
      NMSAVE='proc\f15.dat'
      TREST=0.
      WRITE(4)NMSAVE,TREST
C
      CALL LGSTOP
      STOP
      END
