#
# This makefile was expanded from makefile-1 by Telelogic.
# Expanded macros and dependencies may be found at the
# end of this file
#



#CFLAGS = -g -Wall

CFLAGS = "-Wall -D${OS}"
FFLAGS = "-fno-automatic -fno-automatic"

CC = gcc
FF = g77
LIBS =  -l..\libs_dir\legolib\legolib.lib
INCLUDES =
OBJS = 
SRCS = "edi14.for  lg1.for  lg2.for  lg3.for  lg4.for  lg5.for"
HDRS =  


all: edi14 lg4 lg1.o lg2.o lg3.o lg5.o

# The variable $@ has the value of the target. In this case $@ = i32i5
edi14: edi14.o ${OBJS}
	${CC} ${CFLAGS} ${INCLUDES} -o $@ edi14.o ${OBJS} 

lg4: lg4.o ${OBJS}
	${CC} ${CFLAGS} -o $@ lg4.o ${OBJS} ${LIBS}

.c.o:
	${CC} ${CFLAGS} ${INCLUDES} ${LIBS} -c $<

install: 
	cp edi14 ${LG_LEGO}
	cp lg4   ${LG_LEGO}
	cp lg1.o ${LG_LEGO}
	cp lg2.o ${LG_LEGO}
	cp lg3.o ${LG_LEGO}
	cp lg5.o ${LG_LEGO}

depend: 
	makedepend ${SRCS}

clean:
	rm *.o core *~

tar:
	tar cf code.tar  Makefile *.c *.h testfile1

print:
	more Makefile $(HDRS) $(SRCS) | enscript -2r -p listing.ps


# DO NOT DELETE




# ******* Telelogic expanded section *******

# make_macros from project "Alg_legopc-2007A1_RHE4_lomgr
#CFLAGS = -g -Wall
F_FLAGS=-fno-second-underscore -g -fno-automatic -finit-local-zero
CFLAGS = -Wall -DLinux
CC = gcc
