#
# This makefile was expanded from Makefile-2 by Telelogic.
# Expanded macros and dependencies may be found at the
# end of this file
#

#
#	Makefile Header:               Makefile
#       Subsystem:              28
#       Description:
#       %created_by:    zanna %
#       %date_created:  Mon Jun 17 11:53:36 1996 %
FFLAGS= $(F_FLAGS) 
SORGENTI_FOR= $(LEGOCAD_USER)/legocad/libut_reg/libreg/modrvar.f \
	      $(LEGOCAD_USER)/legocad/libut_reg/libreg/modrdat.f
OGGETTI_FOR= modrvar.o  \
	     modrdat.o
SORGENTI_C= $(LEGOCAD)/regoserver/regoserver.c 
$(LEGOCAD_USER)/legocad/libut_reg/libreg/regoserver: $(OGGETTI_FOR) $(SORGENTI_C)
	$(CC) $(SORGENTI_C) modrvar.o modrdat.o \
              $(LEGOCAD_USER)/legocad/libut_reg/libreg/reglib.a \
              $(LEGO_LIB)/legolib.a \
	      $(LEGO_LIB)/vapo.a -lm $(LIBOTS) $(FC_LIBS) -o $@

modrvar.o :  $(LEGOCAD_USER)/legocad/libut_reg/libreg/modrvar.f
	$(FC) $(F_FLAGS) -c $(LEGOCAD_USER)/legocad/libut_reg/libreg/modrvar.f
modrdat.o : $(LEGOCAD_USER)/legocad/libut_reg/libreg/modrdat.f
	$(FC) $(F_FLAGS) -c $(LEGOCAD_USER)/legocad/libut_reg/libreg/modrdat.f

# ******* Telelogic expanded section *******

# make_macros from project "legocad-2007A1_RHE4_lomgr
GUI_BUILD=/usr/bin/aic
OS=LINUX
X_LIB=-L/usr/X11R6/lib -lMrm -lXm -lXt -lX11
GCC_INCLUDE=
X_INCLUDE=-I. $(GCC_INCLUDE) 
#C_FLAGS=-g -D_BSD -DLINUX -D_NO_PROTO -DXOPEN_CATALOG -DUNIX -Dmmap=_mmap_32_ $(X_INCLUDE) 
C_FLAGS=-g -DDEBUG -D_BSD -DLINUX -D_NO_PROTO -DXOPEN_CATALOG -DUNIX -Dmmap=_mmap_32_ $(X_INCLUDE) 
#C_FLAGS=-g -D_BSD -DLINUX -D_NO_PROTO -DXOPEN_CATALOG -DUNIX -Dmmap=_mmap_32_ $(X_INCLUDE) 
#X_INCLUDE=. -I/usr/include/uil -I/usr/include/Xt -I/usr/include/lib -I$(HHHOME)/include -DOSF1
VERSIONE=-DBANCO_MANOVRA -DSCADA -DBACKTRACK -DF22_APPEND -DSNAP_PIAC -DPIACENZA -DREPLAY -DMFFR -DSAVEPERT
UIL_INCLUDE=-I/usr/include/uil
UIL_COMPILER=/usr/bin/X11/uil
X_FLAGS=-c -D_NO_PROTO -DSNAPSHOT
#F_FLAGS=-lfor
F_LIB=-lg2c -lm
MOTIF_VER=11
HHHOME=$(TOOLS)/hyperhelp
HYPERHELP_OBJ = $(HHHOME)/winhelp/decaosf/winhelp.o
UXCGEN=run_uxcgen.sh $@ $<
#------------------------ C preprocessor
CPP=cpp
#CPPFLAGS=-P -C -DLINUX
#------------------------ C compiler
#CC=cc
#CFLAGS=$(C_FLAGS)
#.c.o:
#	$(CC) -c $(CFLAGS) $< -o $@
#------------------------ Fortran compiler (g77)
F_FLAGS=-fno-second-underscore
